### ISSUE TITLE
[SDK]: 新版Go SDK不支持simulateAndExecute

### ISSUE THREAD

**Issue by 17y** [bianjieai/opb-faq#100]
### 问题描述：
Go SDK不支持simulateAndExecute

### 期望结果：
可以恢复v0.1.0版本的逻辑

### 补充信息：
原有的irita-sdk-go中factory的逻辑在core-sdk-go中被删掉了
https://github.com/bianjieai/irita-sdk-go/blob/455f2040d038f08bdfcbb853eedb372b65447e40/client/tx/factory.go#L177

**Comment by Cyilong** [comment]
你好，目前版本还没有支持这个功能，下一个版本会添加上的

**Comment by 17y** [comment]
> 你好，目前版本还没有支持这个功能，下一个版本会添加上的

了解，请问下下版有预计的发版时间吗？

**Comment by Cyilong** [comment]
你好，经过我们内部调研评审，考虑到文昌链近期升级会对每笔交易 gas 费用进行调整，opb-sdk 将可能不再需要此功能了，因此我们暂时不考虑添加此功能了。后期如有更变，请关注文昌链更新通告。

**Comment by 17y** [comment]
> 你好，经过我们内部调研评审，考虑到文昌链近期升级会对每笔交易 gas 费用进行调整，opb-sdk 将可能不再需要此功能了，因此我们暂时不考虑添加此功能了。后期如有更变，请关注文昌链更新通告。

您的意思是说，文昌链可能会改为每笔固定gas吗
