### ISSUE TITLE
[SDK]: opb-sdk 创建存证 报错

### ISSUE THREAD

**Issue by WangJh1031** [bianjieai/opb-faq#103]
在创建存证的时候 有时候会报 timed out waiting for tx to be included in a block  有时候会报 wrong sequence, will retry address=**** attempts=0 err="incorrect account sequence"
 
但是有时候报错了 但实际是成功的，有时候 又是不成功的  然后也没有返回任何 hash给我 

如何规避这类问题，或者如何异步查询到是否成功了？

**Comment by sin3A** [comment]
创建存证返回信息解析部分逻辑已更新，可以获取opb-sdk-go的最新代码

**Comment by prolenking** [comment]
1. `timed out waiting for tx to be included in a block` 这个错误只有在使用commit模式的时候会出现，可以尝试使用sync模式。
2. 关于sync模式下通过交易hash异步查询的方式，如果是使用opb-sdk-go的话，可以参考example包下的示例；如果是使用opb-sdk-java的话，在sync模式成功发送交易的情况下，可以获取到交易hash，用此hash可以查询交易
