### ISSUE TITLE
[Avata]: 查询 NFT 报错 404

### ISSUE THREAD

**Issue by oyteng1990** [bianjieai/opb-faq#105]
### 环境：
JAVA

### 问题描述：
有部分用户反馈当用户在进行赠送操作的时候，通过NFTID查询NFT的时候链上返回报404的错误问题，有部分用户不会产生此类问题，请帮忙 尽快排查一下，谢谢！
![b6929c75001fcff328d06db01164d40](https://user-images.githubusercontent.com/109779527/180359575-a955e236-73b1-455c-8281-67b77a6707f6.png)

### 期望结果：
希望能尽快的解决这个问题，保证用户的体验

### 复现步骤：
LogClientHttpRequestInterceptor.RestLog(reqUrl=https://apis.avata.bianjie.ai/v1beta1/nft/nfts?class_id=avata4lmvzqsc6yoadfaeo4sa0vcqole&id=avatap9pvfb7lygbsdjqrmiblnu3w4vt, method=GET, headers=[Accept:"application/json, application/*+json", X-Api-Key:"a2I2u067b1c4a0R250H9b5p2u6r9R5S", X-Timestamp:"1658458219982", X-Signature:"f5ef1d3baebbe0cc1126c50dee17cb230295e16eb4afcbbc36bb9a75ba5ea10a", Content-Length:"0"], reqBody=, resBody=404 page not found, costTime=181, resStatus=404)
org.springframework.web.client.HttpClientErrorException$NotFound: 404 Not Found: [404 page not found
]
 
以上这是报错的内容
调的接口：https://apis.avata.bianjie.ai/v1beta1/nft/nfts?class_id=avata4lmvzqsc6yoadfaeo4sa0vcqole&id=avatap9pvfb7lygbsdjqrmiblnu3w4vt
参数是 ：
class_id=avata4lmvzqsc6yoadfaeo4sa0vcqole
id=avatap9pvfb7lygbsdjqrmiblnu3w4vt
返回报错信息：404 Not Found: [404 page not found

**Comment by deadfiish** [comment]
您好，使用提供的参数暂时没能复现这个问题。java 是用的文档提供的 demo 吗？我们测试一下
