### ISSUE TITLE
[Avata]: MT类别创建时没有要输入类别ID，返回值也没有类别ID，为什么发行时候有类别ID

### ISSUE THREAD

**Issue by lokami** [bianjieai/opb-faq#108]
![image](https://user-images.githubusercontent.com/10710795/181072555-ef12b7e1-7348-432d-a80d-44f321764e4c.png)
![image](https://user-images.githubusercontent.com/10710795/181072613-cff3d8b3-ae86-499e-9626-bac1c9bdc31b.png)
![image](https://user-images.githubusercontent.com/10710795/181072651-50278af0-4506-44d6-a12b-a752664024c5.png)
如截图这样，发行参数没有找到类别ID在哪里，为啥后续操作却有类别ID

**Comment by lokami** [comment]
怎么刚问完不久就发现文档改了，即将上线是什么时候啊，我现在对接是废了吗？当前接口还能否使用

**Comment by deadfiish** [comment]
1.文档没有变动，你看的是两个不同环境的文档。测试环境 MT 已经上线，生产环境还没上线，预计在下周上线。
2.Avata 是异步上链的，所以在调用交易接口后（比如创建 MT 类别接口、发行 MT 接口等等），需要用上链交易结果查询接口查询交易结果，交易成功，会返回 class_id。交易成功后，也能通过查询 MT 类别接口或查询 MT 类别详情接口查询类别信息。
