### ISSUE TITLE
[Avata]: 创建NFT类别有扣费，但是查询不到类别明细，并且查询类别列表时返回的都不是我名下的类别

### ISSUE THREAD

**Issue by lokami** [bianjieai/opb-faq#109]
创建NFT类别的时候有正常扣费，但是没有创建出来，查询不到，在测试环境跑通了，正式环境创建却没有。

根据类别ID查询的时候，提示 resource not found, class_id: xxx not found

导致无法发行NFT

根据创建时返回的ID，调用上链交易结果查询返回如下
{
    "type": "issue_class",
    "tx_hash": "",
    "status": 3,
    "class_id": "",
    "nft_id": "",
    "message": "",
    "block_height": 0,
    "timestamp": "",
    "tag": null
}

基本只知道status = 3有用，但是不知道它代表啥。我同样的参数在正式环境下还可以调用成功并且扣费，但是测试环境却会提示重复提交，并且能够查询类别结果

然后调用 查询 NFT 类别 列表，返回的都不是我账号名下的类别，我盲猜是链上所有的NFT类别，根据我的条件进行筛查也查询不到我创建的类别，想知道这个类被列表查询出来的结果是正常的吗？按理应该是查询我名下的资产才对

以下是查询列表返回的数据
{
  "data": {
    "offset": 0,
    "limit": 10,
    "total_count": 878724,
    "classes": [
      {
        "id": "nft993u03nn29sd83mntah7is9tr4",
        "name": "55286",
        "owner": "iaa1yfth285x6qgpvstukjefqd69yqx4mvuas69yez",
        "tx_hash": "F6D4D5C0C82AC88F1F223288D68294E305FFF0D6AA16C9F2ED15BCD1F69CC576",
        "symbol": "",
        "nft_count": 0,
        "uri": "",
        "timestamp": "2022-07-29 11:28:58 +0000 UTC"
      },
      {
        "id": "avatarzrbnwzhyf9tvltndf0wsv4usdj",
        "name": "测试1111",
        "owner": "iaa1k4arnmakcqejzvhezndfvr4y52pu2ddj9ruj8u",
        "tx_hash": "4E4E2D4CE82EDF0E133200BE2C63CFBBFAFFBC315914C52157EAC77371EC1539",
        "symbol": "测试1111",
        "nft_count": 0,
        "uri": "",
        "timestamp": "2022-07-29 11:28:58 +0000 UTC"
      },
      {
        "id": "nft9ovdqg67gu4dfq8m7cp14g8084",
        "name": "55270",
        "owner": "iaa1yn3g7crjce9tycj8pklpapq0gd5qgazs9nrqfe",
        "tx_hash": "0CD49824265CCC1ADBC20AD9EE0F0FCE08C16CDC99AE47F916D7D2FD7C6D219A",
        "symbol": "",
        "nft_count": 0,
        "uri": "",
        "timestamp": "2022-07-29 11:28:53 +0000 UTC"
      },
      {
        "id": "nftth68t9ha1oaa0aocdjmppvq174",
        "name": "53761",
        "owner": "iaa1fd6wdcqngdels5ywktz2x9c4eche9eevvmlkwg",
        "tx_hash": "81FB3B37137153A7590C34627D1DD25C4F09052A37EB83A9F748C5A51C232F75",
        "symbol": "",
        "nft_count": 0,
        "uri": "",
        "timestamp": "2022-07-29 11:28:53 +0000 UTC"
      },
      {
        "id": "nftjfddsfggg06h5spnsvrbmjmqvv",
        "name": "55145",
        "owner": "iaa1wuxn32m8x5rtlsc7e0u7ne0xmndnlvpg0me649",
        "tx_hash": "3E0FB65EFD61CB5979BFBF09C6D5937BA36466439CF2B141F0336A2CFA6B6651",
        "symbol": "",
        "nft_count": 0,
        "uri": "",
        "timestamp": "2022-07-29 11:28:53 +0000 UTC"
      },
      {
        "id": "nftc8i5sfmdasbjtv4b4aq162k8mf",
        "name": "53228",
        "owner": "iaa1yrapxf0xtjufv57awv50xecd0gzy75ekk4dnul",
        "tx_hash": "74A847B972084299109509B3380045E5B8F92BA97587CE7CBA5CBB3A3A6C1EE7",
        "symbol": "",
        "nft_count": 0,
        "uri": "",
        "timestamp": "2022-07-29 11:28:53 +0000 UTC"
      },
      {
        "id": "nfttr8ca1ftk5g3b90oj8v65lalni",
        "name": "55279",
        "owner": "iaa1h2u7vuht9cjeyw8lp4ef505mylltc0dnu8l49c",
        "tx_hash": "4F9D9349D0E19FB35E582C67231FC1C0BAF684695CF4B753D2FA3B049669756B",
        "symbol": "",
        "nft_count": 0,
        "uri": "",
        "timestamp": "2022-07-29 11:28:53 +0000 UTC"
      },
      {
        "id": "nftvrfvnd06f5c3ambohouj5kjsgf",
        "name": "42945",
        "owner": "iaa17gw2q2p6flrsp3vd9cztl5arw4lqvddkcrz8mg",
        "tx_hash": "F72C82CD95672F089E9E0ACFD9D46FE35110C6A80B7BFB0BE5B33129291598C9",
        "symbol": "",
        "nft_count": 0,
        "uri": "",
        "timestamp": "2022-07-29 11:28:53 +0000 UTC"
      },
      {
        "id": "nft9pbgq0v7iqq6puo87gqigbnos1",
        "name": "53198",
        "owner": "iaa1xrge47g4rppq2hst3xy0lrmqkqcw23w9dcux9y",
        "tx_hash": "C233BA8824188E06D405699C77AA0EC8B1DD5A961372096565889132CA0D3A66",
        "symbol": "",
        "nft_count": 0,
        "uri": "",
        "timestamp": "2022-07-29 11:28:53 +0000 UTC"
      },
      {
        "id": "nftmnfi7u1envnnu199pnvt3ak9bu",
        "name": "55272",
        "owner": "iaa1ec650ceva7duwnu23qteystvn302njnv3cdc0s",
        "tx_hash": "A2BE7F50C9B00D8AB182A6983D346D0FBA8DFEE7F860BE78CF526A5CC6808AE4",
        "symbol": "",
        "nft_count": 0,
        "uri": "",
        "timestamp": "2022-07-29 11:28:53 +0000 UTC"
      }
    ]
  }
}

**Comment by deadfiish** [comment]
status = 3 是交易正在等待处理，还没上链，所以查询不到。查询类别列表接口返回的是整个 Avata 平台的类别，而不是应用方下的类别。

**Comment by lokami** [comment]
> status = 3 是交易正在等待处理，还没上链，所以查询不到。查询类别列表接口返回的是整个 Avata 平台的类别，而不是应用方下的类别。

这个一般是多久上链啊，我当时等了几个小时都没有结果，但是今天发现上链了

**Comment by deadfiish** [comment]
正常情况下是秒级。有可能当天的交易量非常大，导致队列中排队上链的交易太多，这两天应该没有这么拥堵的情况了。我们会不断进行优化的。

**Comment by Bai8baozhou** [comment]
@deadfiish 相同问题

```
RFn3vSegRmoxiQUAn1nTOMasB_oDbfwX
kDVxjmKBwHQG-Rnq1BLpsdyAM9YTDduy
25hZ3FA_epgAnjnRa3Xy2sbUQbLTzyOg
```
这三个 operation_id 的 status = 3 一直没有上链成功，都是创建 NFT 类别

请问要多久才能排上队呀？
