### ISSUE TITLE
[Avata]: 查看合约地址步骤

### ISSUE THREAD

**Issue by XiaoHuiBuHui** [bianjieai/opb-faq#110]
1.Avata 原生NFT 项目
  原生数据对象的数据类别相当于合约，把数据对象的数据类别在浏览器上详情的整个网页链接就可以作为合约地址，1.2整个链接，可以视为合约地址。

  从【文昌链浏览器】选择应用使用的【数据类别】详情地址（您可填写该数据类别详情的浏览器网页链接，如1.2示例）

1.1文昌链浏览器数据类别查询：
https://explorer.wenchang.bianjie.ai/#/denoms

1.2数据类别详情地址示例：
https://explorer.wenchang.bianjie.ai/#/tx?txHash=2E6D1983C66081FCF6C67030D4DDC47A71671C1E0E7AB39C8C452A1DAA0BC96C

2.Avata DDC 项目
Avata  DDC 项目使用的是 BSN DDC 官方合约地址，合约地址如下 ：
https://ddc.bsnbase.com/static/tmpFile/bzsc/09DeveloperData/9-3.html

**Comment by jianzi0307** [comment]
```
1.Avata 原生NFT 项目
原生数据对象的数据类别相当于合约，把数据对象的数据类别在浏览器上详情的整个网页链接就可以作为合约地址，1.2整个链接，可以视为合约地址。
```
原生数据对象的数据类别，不是用户提交的NFT类别ID：class_id 吗，可以做合约吗？
![image](https://user-images.githubusercontent.com/2997173/182342625-63221a1c-dcd8-4bf2-9b4b-707cf9e80247.png)


```
1.2数据类别详情地址示例：
https://explorer.wenchang.bianjie.ai/#/tx?txHash=2E6D1983C66081FCF6C67030D4DDC47A71671C1E0E7AB39C8C452A1DAA0BC96C
```

这个合约地址咋是个链接？
不应该是【0x354c6a.....F2870 】这种格式的串吗？

**Comment by deadfiish** [comment]
![image](https://user-images.githubusercontent.com/94030704/183577550-1934cf46-a29e-4709-9eaa-8ed90f457b9b.png)
