### ISSUE TITLE
[SDK]: 无法接入文昌正式链rpc

### ISSUE THREAD

**Issue by LeeJongSonk** [bianjieai/opb-faq#111]
测试链可以正常连接，测试接口。
正式链使用ws连接的时候提示：rpc error: code = Unavailable desc = failed to receive server preface within timeout
使用http请求的时候等了很久提示：panic: malformed HTTP response "\x15\x00\x00\x00\x02\x01\x00"
使用参数如下：
wsAddress   = fmt.Sprintf("%s/api/%s/ws", "wss://opbningxia.bsngate.com:18602", projectId)
rpcAddress  = fmt.Sprintf("%s/api/%s/rpc", "https://opbningxia.bsngate.com:18602", projectId)
grpcAddress = "opbningxia.bsngate.com:18603"
chainID     = "wenchangchain"

algo             = "sm2"

测试代码：
![image](https://user-images.githubusercontent.com/88018698/182752090-39825829-ba31-477d-965b-dba81155195a.png)

**Comment by sin3A** [comment]
将type.WSAddrOperation的注释打开，把ws的配置添加进去

**Comment by sin3A** [comment]
> 测试链可以正常连接，测试接口。 正式链使用ws连接的时候提示：rpc error: code = Unavailable desc = failed to receive server preface within timeout 使用http请求的时候等了很久提示：panic: malformed HTTP response "\x15\x00\x00\x00\x02\x01\x00" 使用参数如下： wsAddress = fmt.Sprintf("%s/api/%s/ws", "wss://opbningxia.bsngate.com:18602", projectId) rpcAddress = fmt.Sprintf("%s/api/%s/rpc", "https://opbningxia.bsngate.com:18602", projectId) grpcAddress = "opbningxia.bsngate.com:18603" chainID = "wenchangchain"
> 
> algo = "sm2" projectId = "aea8b6*******9d69af4d5762f" projectKey = "84b6a63********440613d071" chainAccountAddr = "iaa18h9zwu0ywzj4gj7jktk37tzy8nvluhxv6svwl2"
> 
> 测试代码： ![image](https://user-images.githubusercontent.com/88018698/182752090-39825829-ba31-477d-965b-dba81155195a.png)

请注意保护敏感信息

**Comment by LeeJongSonk** [comment]
> 84b6a6329f0f4c2d9b0400440613d071

![image](https://user-images.githubusercontent.com/88018698/182755084-1886225b-379c-422f-abbb-5f927a8dc0c2.png)
账户查询失败: rpc error: code = Unavailable desc = failed to receive server preface within timeout
打开注释了  但是还是说这句话  是什么意思呢？

**Comment by sin3A** [comment]
根据提供参数并未复现提到的问题，测试初始化配置可以参考：
fee, _ := types.ParseDecCoins("200000ugas") // 设置文昌链主网的默认费用，10W不够就填20W，30W....
	// 初始化 SDK 配置
	options := []types.Option{
		types.AlgoOption(algo),
		types.KeyDAOOption(store.NewMemory(nil)),
		types.FeeOption(fee),
		types.TimeoutOption(10),
		types.CachedOption(true),
		types.WSAddrOption(wsAddress),
	}
	cfg, err := types.NewClientConfig(rpcAddress, grpcAddress, chainID, options...)
	if err != nil {
		panic(err)
	}

	// 初始化 OPB 网关账号（测试网环境设置为 nil 即可）
	authToken := model.NewAuthToken(projectId, projectKey, chainAccountAddr)

	// 开启 TLS 连接
	// 若服务器要求使用安全链接，此处应设为true；若此处设为false可能导致请求出现长时间不响应的情况
	authToken.SetRequireTransportSecurity(true)
	// 创建 OPB 客户端
	client := opb.NewClient(cfg, &authToken)

**Comment by LeeJongSonk** [comment]
> 根据提供参数并未复现提到的问题，测试初始化配置可以参考： fee, _ := types.ParseDecCoins("200000ugas") // 设置文昌链主网的默认费用，10W不够就填20W，30W.... // 初始化 SDK 配置 options := []types.Option{ types.AlgoOption(algo), types.KeyDAOOption(store.NewMemory(nil)), types.FeeOption(fee), types.TimeoutOption(10), types.CachedOption(true), types.WSAddrOption(wsAddress), } cfg, err := types.NewClientConfig(rpcAddress, grpcAddress, chainID, options...) if err != nil { panic(err) }
> 
> ```
> // 初始化 OPB 网关账号（测试网环境设置为 nil 即可）
> authToken := model.NewAuthToken(projectId, projectKey, chainAccountAddr)
> 
> // 开启 TLS 连接
> // 若服务器要求使用安全链接，此处应设为true；若此处设为false可能导致请求出现长时间不响应的情况
> authToken.SetRequireTransportSecurity(true)
> // 创建 OPB 客户端
> client := opb.NewClient(cfg, &authToken)
> ```

可以了 谢谢 我把wsaddress传入接口了 原来接口里要用rpcaddress
