### ISSUE TITLE
创建nft类别失败，

### ISSUE THREAD

**Issue by wozuiyangqi** [bianjieai/opb-faq#116]
### 问题描述：
创建nft类别失败，
{"data":"test","description":"测试类别","name":"test","operation_id":"1662366153841","owner":"为控制台的-链账户管理-我的链账户-链账户地址","symbol":"tes","uri":"https://test.out.uri","uri_hash":"test"}

{"error":{"code_space":"NFTP-OPEN-API","code":"FORBIDDEN","message":"authentication failed"}}

### 期望结果：
希望能创建成功

### 复现步骤：

1. 启动程序
2. /v1beta1/nft/classes 这个接口 post请求
3.{"data":"test","description":"测试类别","name":"test","operation_id":"1662366153841","owner":"控制台-链账户管理-我的链账户-链账户地址","symbol":"tes","uri":"https://test.out.uri","uri_hash":"test"}
4. {"error":{"code_space":"NFTP-OPEN-API","code":"FORBIDDEN","message":"authentication failed"}}

**Comment by XiaoHuiBuHui** [comment]
参考下：https://github.com/bianjieai/opb-faq/issues/13
