### ISSUE TITLE
[Java]如何在调用solidity合约的同时还能使用代付功能

### ISSUE THREAD

**Issue by DavyVan** [bianjieai/opb-faq#117]
### 环境：

- OPB-SDK：v0.1.11

### 问题描述：
请问如何使用Java调用自己部署的EVM solidity合约并同时使用代付功能？

**Comment by XiaoHuiBuHui** [comment]
EVM 模块不支持代付。

**Comment by DavyVan** [comment]
也就是说如果想用代付就只能使用原生NFT或者MT模块了？

**Comment by XiaoHuiBuHui** [comment]
是的
