### ISSUE TITLE
[Avata]: [标题]区块链合作协议申请

### ISSUE THREAD

**Issue by 05Martin** [bianjieai/opb-faq#118]
### 问题描述：
您好，我司已通过邮箱caiiwolf@163.com申请区块链合作协议，客服联系不上，烦请看一下能否更快些回复，急用

**Comment by XiaoHuiBuHui** [comment]
Avata 服务平台控制台已支持自助申请【合作协议】
https://forum.avata.bianjie.ai/t/topic/44
