### ISSUE TITLE
【NFT】NFT类别（denom）的修改与转让

### ISSUE THREAD

**Issue by jeff-zixuan** [bianjieai/opb-faq#14]
1. NFT类别是否可以修改？
答：链上信息不能修改，链外信息可以修改，描述性的信息都在链外，即可以理解为能够修改。

2. 如果有修改NFT类别的需求，在实际操作时新生成一个NFT类别，那么原有NFT类别下的那些NFT，有没有可能通过编辑NFT的办法，使其归到新的NFT类别下面？
答：如果 NFT 类别对应的链外信息可以通过修改满足需求，就不存在这个问题了。

3. NFT类别如果转让，转让以后，原先持有这一方还能在这个NFT类别下发NFT么？转让以后原先这些NFT会不会也跟着转让？
答：NFT 类别在创建时，可以指定是否允许类别 Owner 以外的人在此类别中发行 NFT（**创建后不可改**）；
    - 如果允许，则类别被转让后，原 Owner 仍然可以在此类别中发行 NFT；
    - 如果不允许，则类别被转让后，原 Owner 不能在此类别中发行 NFT；

**小结**：如果业务应用方为了后面可以对NFT类别和NFT本身进行各种修改，那就在设计时把有可能会变化的内容放在链外，即可满足实际业务需求。

**Comment by sin3A** [comment]
创建denom的时候，设置该denom的发行限制和更新限制
IssueDenomRequest req = new IssueDenomRequest();
        req.setId(denomID);
        req.setName(denomName);
        // 是否限制发行，true：只有Denom所有者介意发行此类别NFT，false：任何人都可以发行NFT
        req.setMintRestricted(false);
        //是否限制更新，true：此类别中任何人都不可以更新NFT，false：只有次NFT所有者才能更新
        req.setUpdateRestricted(false);
        req.setSchema(schema);
[link](https://github.com/bianjieai/opb-sdk-java/blob/master/src/test/java/irita/sdk/NftTest.java)

**Comment by deadfiish** [comment]
irita 命令行创建 denum
Usage:
irita tx nft issue [denom-id] [flags]

Examples:
irita tx nft issue <denom-id> --from=<key-name> --name=<denom-name> --symbol=<denom-symbol> --mint-restricted=<mint-restricted> --update-restricted=<update-restricted> --schema=<schema-content or path to schema.json> --chain-id=<chain-id> --fees=<fee>

test：
irita tx nft issue ysmid --from=node0 --name ysmname --chain-id=ysmtest --mint-restricted=false --update-restricted=false --fees=10uirita  --node tcp://127.0.0.1:26657 -y -b block

具体 flags 含义如下：
Flags:
  -a, --account-number uint      The account number of the signing account (offline mode only)
  -b, --broadcast-mode string    Transaction broadcasting mode (sync|async|block) (default "sync")
      --data string              The data is the app specific metadata of the NFT class. Optional
      --description string       The description is a brief description of nft classification. Optional
      --dry-run                  ignore the --gas flag and perform a simulation of a transaction, but don't broadcast it
      --fee-account string       Fee account pays fees for the transaction instead of deducting from the signer
      --fees string              Fees to pay along with transaction; eg: 10uatom
      --from string              Name or address of private key with which to sign
      --gas string               gas limit to set per-transaction; set to "auto" to calculate sufficient gas automatically (default 200000)
      --gas-adjustment float     adjustment factor to be multiplied against the estimate returned by the tx simulation; if the gas limit is set manually this flag is ignored  (default 1)
      --gas-prices string        Gas prices in decimal format to determine the transaction fee (e.g. 0.1uatom)
      --generate-only            Build an unsigned transaction and write it to STDOUT (when enabled, the local Keybase is not accessible)
  -h, --help                     help for issue
      --keyring-backend string   Select keyring's backend (os|file|kwallet|pass|test|memory) (default "os")
      --keyring-dir string       The client Keyring directory; if omitted, the default 'home' directory will be used
      --ledger                   Use a connected Ledger device
      --mint-restricted          mint restricted of nft under denom
      --name string              The name of the denom
      --node string              <host>:<port> to tendermint rpc interface for this chain (default "tcp://localhost:26657")
      --note string              Note to add a description to the transaction (previously --memo)
      --offline                  Offline mode (does not allow any online functionality
  -o, --output string            Output format (text|json) (default "json")
      --schema string            Denom data structure definition
  -s, --sequence uint            The sequence number of the signing account (offline mode only)
      --sign-mode string         Choose sign mode (direct|amino-json), this is an advanced feature
      --symbol string            The symbol of the denom
      --timeout-height uint      Set a block timeout height to prevent the tx from being committed past a certain height
      --update-restricted        update restricted of nft under denom
      --uri Data                 The uri for the class metadata stored off chain. It can define schema for Class and NFT Data attributes. Optional
      --uri-hash string          The uri-hash is a hash of the document pointed by uri. Optional
  -y, --yes                      Skip tx broadcasting prompt confirmation

Global Flags:
      --chain-id string     The network chain ID
      --home string         directory for config and data (default "/home/ysm/.irita")
      --log_format string   The logging format (json|plain) (default "plain")
      --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
      --trace               print out full stack trace on errors
