### ISSUE TITLE
接口模式

### ISSUE THREAD

**Issue by UpdateCw** [bianjieai/opb-faq#25]
1.我一次性铸造500个，是需要调用500次接口哇，然后指向的藏品文件是同一个，只是藏品hash不同？
2.现在流行的盲盒玩法：有3个低级藏品可以合成1个高级藏品，一般合成的时候会把3个低级藏品销毁，然后再给用户一个高级藏品
这里技术实现上就是先「销毁」3个藏品，然后「转移」一个已经「提前创建」的高级藏品给到用户？

麻烦回答下 谢谢

**Comment by zhangyelong** [comment]
1. 是的，每个 NFT 都有一个独一无二的 ID，当然你可以设置这 500 个 NFT 的文件为同一个
2. 是的，「销毁」 3 个并「转移」1 个提前创建的 NFT，或者也可以是「销毁」3 个并「发行」1 个新创建的 NFT 到指定账户
