### ISSUE TITLE
测试https://stage.apis.avata.bianjie.ai/v1beta1/nft/classes（创建 NFT 类别），报错

### ISSUE THREAD

**Issue by huangtb** [bianjieai/opb-faq#28]
您好，我参考接口文档，
<img width="929" alt="image" src="https://user-images.githubusercontent.com/19970292/166852678-a8d23bac-35e6-4454-80d9-a0d83d328c7b.png">
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/19970292/166852841-9635545b-0657-4a78-8d4d-bc595a23051c.png">

请求接口
https://stage.apis.avata.bianjie.ai/v1beta1/nft/classes

请求报文
{"name":"数字藏品Test","operation_id":"202204290344","owner":"marz"}

报错内容
{"error":{"code_space":"NFT","code":"PARAMS_ERROR","message":"the recipient address does not meet the specification of the current chain"}}

请问这是什么原因呢，期待回复，谢谢！

**Comment by lyaojin** [comment]
你好 ， 我最近也在按照这个文档做开发 ， 请问你的NFT账号创建成功了吗？如果成功了能帮忙发一个示例吗？
或者你的联系方式，后面可以交流NFT对接开发过程中的而相关问题 。

**Comment by huangtb** [comment]
我没有通过DEMO测试创建账号，客服那边给了ak和 sk，你可以留下微信我加下你。

**Comment by lyaojin** [comment]
qh930428

**Comment by duanhairui** [comment]
![image](https://user-images.githubusercontent.com/56431806/168715011-46a8753d-8f67-4727-8006-cf492f403aec.png)
