### ISSUE TITLE
正式环境创建账号报错

### ISSUE THREAD

**Issue by UpdateCw** [bianjieai/opb-faq#29]
说明：代码相同，只修改了正式测试请求地址，以及apiKey、signatureKe
          并且账户有钱，充值了5000

测试环境：
  响应数据：{"data":{"accounts":["iaa1lrp83d0kwqudmkhm77hytc0drsk9z5mlsdzr0z"]}}
正式环境：
  响应数据：{"error":{"code_space":"NFTP-OPEN-API","code":"FORBIDDEN","message":"authentication failed"}}

**Comment by duanhairui** [comment]
如果测试环境验证正常，生产环境报错，可用下述的工具包生成一个签名哈希，与程序中的哈希进行比对：
Java 可以直接用这个工具包，参考测试用例把参数换成自己的试试：https://github.com/bianjieai/avata-auth/blob/master/avata-auth-java/src/test/java/AvataUtilsTest.java
如果还有问题，可联系技术同学进行问题排查，看是否为参数错误
