### ISSUE TITLE
创建NFT类别报错403

### ISSUE THREAD

**Issue by lyaojin** [bianjieai/opb-faq#30]
创建NFT类别报错403 
{"error":{"code_s
pace":"NFTP-OPEN-API","code":"FORBIDDEN","message":"authentication failed"}}
![image](https://user-images.githubusercontent.com/65711260/167243419-7eba4be5-1808-4fac-95e0-dc1015de8249.png)

接口请求地址：https://stage.apis.avata.bianjie.ai/v1beta1/nft/classes
heads: 
{
 X-Timestamp=1651906921211,
 X-Signature=bdb4ef21949b996e7e31b933529636b9eda704e37d6e09fe64907165fef2e280, 
 X-Api-Key=y680WS4FZCywcRB4irMM***********, 
 Content-Type=application/json;charset=UTF-8
}
请求参数Map对象: {
 owner=iaa1vvdyc2hf0q2w2e************8r8pg4da2h, 
 symbol=MBOX, 
 name=Mobx, 
 operation_id=4c7b83b98c034f2c969b169e921117c7
}
**注：使用相同的方式的更换"接口地址"与"请求参数Map"以后测试调用创建NFT账号接口没问题，可以成功。**

1. 接口文档中没有标记required的字段可以不用传把？
2. 是我的参数Body传入有问题吗？

**Comment by lyaojin** [comment]
示例代码

> public static void main(String[] args) {
        String apiKey = "y680WS4FZCywcRB4irMM3xxxxxx";
        String apiSecret = "g1V2VKTnlWlUzZ2DQd0kxxxxx";
        String url = "https://stage.apis.avata.bianjie.ai";
        //String path = "/v1beta1/accounts";
        String path = "/v1beta1/nft/classes";
        Map<String, Object> param = new HashMap<>();
        param.put("name", "MBOX-ttt");
        param.put("symbol", "MBOX-ttt");
        param.put("owner", "iaa1xd44h5cktcv2f7k96quwpmx2cczkzr48re4aje");
        param.put("operation_id", UUIDUtil.uuid());
        long timeStamp = System.currentTimeMillis();
        String res = HttpRequest.post(url + path)
                .body(JSONObject.toJSONString(param))
                .header("Content-Type", "application/json")
                .header("X-Api-Key", apiKey)
                .header("X-Timestamp", Long.toString(timeStamp))
                .header("X-Signature", AvataUtils.signRequest(path, null, param, timeStamp, apiSecret))
                .execute().body();
        System.out.println(res);
    }

**Comment by MaricoHan** [comment]
你好，不管是哪一个接口，后端都是走的相同的鉴权流程。
这个错误发生的情况是：用户对http请求的签名过程与官方的签名过程不一致！具体见官方的签名过程示例：[API网关签名示例（go、java和php）](https://apis.avata.bianjie.ai/#section/Introduction/API)

> 需要特别注意的是，对http请求签名的过程中包括：url路径、请求参数、请求体、时间戳和api-secret。

目前，根据很多已经解决这个问题的用户来看，都是由于在对http请求签名的过程中，遗漏了其中的某项没有签名导致的！

并且，我们的鉴权流程都是经过高并发测试的，只要是对http请求正确签名，是不会报这个错误的。
所以，当遇到这个问题时，请务必仔细检查您的签名过程，确保与[官方API网关签名示例（go、java和php）](https://apis.avata.bianjie.ai/#section/Introduction/API)一致！

如果实在解决不了，您可以将代码贴出来，我们的技术人员会帮您排查。



> 创建NFT类别报错403 {"error":{"code_s pace":"NFTP-OPEN-API","code":"FORBIDDEN","message":"authentication failed"}} ![image](https://user-images.githubusercontent.com/65711260/167243419-7eba4be5-1808-4fac-95e0-dc1015de8249.png)
> 
> 接口请求地址：https://stage.apis.avata.bianjie.ai/v1beta1/nft/classes heads: { X-Timestamp=1651906921211, X-Signature=bdb4ef21949b996e7e31b933529636b9eda704e37d6e09fe64907165fef2e280, X-Api-Key=y680WS4FZCywcRB4irMM***********, Content-Type=application/json;charset=UTF-8 } 请求参数Map对象: { owner=iaa1vvdyc2hf0q2w2e************8r8pg4da2h, symbol=MBOX, name=Mobx, operation_id=4c7b83b98c034f2c969b169e921117c7 } **注：使用相同的方式的更换"接口地址"与"请求参数Map"以后测试调用创建NFT账号接口没问题，可以成功。**
> 
> 1. 接口文档中没有标记required的字段可以不用传把？
> 2. 是我的参数Body传入有问题吗？

**Comment by MaricoHan** [comment]
> 

1. 这里的`HttpRequest`是自己封装的吗，或者说用的是哪个第三方包吗
2. 请确保请求头里的时间戳和`AvataUtils.signRequest()`方法里的转string的方式一致。官方用的是`String.valueOf(timestamp)`

**Comment by lyaojin** [comment]
1.HttpRequest工具包

**Comment by lyaojin** [comment]
1.HttpResuest工具包
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.3.9</version>
        </dependency>
2.加密算法工具类是使用的官网文档提供的，且用此加密算发调用创建NFT账号接口已成功

**Comment by lyaojin** [comment]
或者您这边可以通过
String apiKey = "y680WS4FZCywcRB4irMM3nUE0YtXAct";
String apiSecret = "g1V2VKTnlWlUzZ2DQd0kGuGNUtlPdui";
然后调用测试环境NFT创建类别接口“/v1beta1/nft/classes”成功的代码示例 ， 我直接用你们提供的也可以 。 麻烦了。

**Comment by lyaojin** [comment]
或者您这边可以通过
String apiKey = "y680WS4FZCywcRB4irMM3nUE0YtXAct";
String apiSecret = "g1V2VKTnlWlUzZ2DQd0kGuGNUtlPdui";
然后调用测试环境NFT创建类别接口“/v1beta1/nft/classes”成功的代码示例 ， 我直接用你们提供的也可以 。 麻烦了。

**Comment by lyaojin** [comment]
![image](https://user-images.githubusercontent.com/65711260/167523625-9c12b8fc-96a9-45ef-a6c1-5169208ba443.png)
我这边修改了operation_id测试还是不行！
1.您的signRequest方法是与官方文档https://apis.avata.bianjie.ai/ 中一直的对吧 ？
![image](https://user-images.githubusercontent.com/65711260/167523792-e98d5a53-7927-4ea0-b910-a32bed3ff357.png)

2.非常抱歉我还是没能找出问题，能否麻烦您远程协助下vx:qh930428

**Comment by MaricoHan** [comment]
好的

**Comment by 519401502** [comment]
请问解决了吗 我也是这么问题

**Comment by MaricoHan** [comment]
```JAVA
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.serializer.SerializerFeature;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HashMap;
import java.util.Map;

public class sign {

    /**
     * 对请求参数进行签名处理
     *
     * @param path      请求路径，仅截取域名后及 Query 参数前部分，例："/v1beta1/accounts";
     * @param query     Query 参数，例："key1=value1&key2=value2"，需转为 Map 格式
     * @param body      Body 参数，例："{\"count\": 1, \"operation_id\": \"random_string\"}"，需转为 Map 格式
     * @param timestamp 当前时间戳（毫秒），例：1647751123703
     * @param apiSecret 应用方的 API Secret，例："AKIDz8krbsJ5yKBZQpn74WFkmLPc5ab"
     * @return 返回签名结果
     */
    public static String signRequest(String path, Map<String, Object> query, Map<String, Object> body, long timestamp, String apiSecret) {
        Map<String, Object> paramsMap = new HashMap();
        paramsMap.put("path_url", path);
        if (query != null && !query.isEmpty()) {
            query.forEach((key, value) -> paramsMap.put("query_" + key, value));
        }
        if (body != null && !body.isEmpty()) {
            body.forEach((key, value) -> paramsMap.put("body_" + key, value));
        }
        // 将请求参数序列化为排序后的 JSON 字符串
        String jsonStr = JSON.toJSONString(paramsMap, SerializerFeature.MapSortField);
        // 执行签名
        String signature = sha256Sum(jsonStr + String.valueOf(timestamp) + apiSecret);
        return signature;
    }


    /**
     * SHA256 摘要
     *
     * @param str
     * @return
     */
    private static String sha256Sum(String str) {
        MessageDigest digest = null;
        try {
            digest = MessageDigest.getInstance("SHA-256");
        } catch (NoSuchAlgorithmException e) {
            // Should not happen
            e.printStackTrace();
        }
        byte[] encodedHash = digest.digest(str.getBytes(StandardCharsets.UTF_8));
        return bytesToHex(encodedHash);
    }

    /**
     * 将 bytes 转为 Hex
     *
     * @param hash
     * @return
     */
    private static String bytesToHex(byte[] hash) {
        StringBuilder hexString = new StringBuilder(2 * hash.length);
        for (int i = 0; i < hash.length; i++) {
            String hex = Integer.toHexString(0xff & hash[i]);
            if (hex.length() == 1) {
                hexString.append('0');
            }
            hexString.append(hex);
        }
        return hexString.toString();
    }
}
```

```JAVA
    @Test
    public void sign1(){
        String apiKey = "y680WS4FZCywcRB4irMM3nUE0YtXAct";
        String apiSecret = "g1V2VKTnlWlUzZ2DQd0kGuGNUtlPdui";
        String url = "https://stage.apis.avata.bianjie.ai";
        //String path = "/v1beta1/accounts";
        String path = "/v1beta1/nft/classes";
        Map<String, Object> param = new HashMap<>();
        param.put("name", "MBOX-ttt");
        param.put("symbol", "MBOX-ttt");
        param.put("owner", "iaa1xd44h5cktcv2f7k96quwpmx2cczkzr48re4aje");
        param.put("operation_id", "123123");
        long timeStamp = System.currentTimeMillis();


        String res = HttpRequest.post(url + path)
                .body(JSONObject.toJSONString(param))
                .header("Content-Type", "application/json")
                .header("X-Api-Key", apiKey)
                .header("X-Timestamp", String.valueOf(timeStamp))
                .header("X-Signature", sign.signRequest(path, null, param, timeStamp, apiSecret))
                .execute().body();
        System.out.println(res);
    }
```

**Comment by MaricoHan** [comment]
```POM
		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>fastjson</artifactId>
			<version>1.2.79</version>
		</dependency>
```

**Comment by lyaojin** [comment]
> 问题已解决，针对java版本的签名示例，请使用以下版本的fastjson！！！（涉及到签名过程中的序列化排序）
> 
> ```java
> 	<依赖>
> 		< groupId > com . 阿里巴巴</ groupId >
> 		< artifactId > fastjson </ artifactId >
> 		<版本> 1.2。79 </版本>
> 	</依赖>
> ```

听我说.....谢谢你，谢谢你，温暖了四季..

**Comment by BAige88** [comment]
测试环境报错{"error":{"code_space":"NFTP-OPEN-API","code":"FORBIDDEN","message":"authentication failed"}} #49
public static void main(String[] args) {
		String avata_api_key = "Dyg0F3Oymt71bN4O7FaQljRpKrhUrzT";
		String avata_api_secret = "OfGg5aKrCmGi5jo2TifmUPMyVfMDfVq";
		String timestamp = System.currentTimeMillis()+"";
		String path = AvataConfig.TEST+AvataConfig.ACCOUNTS;
		String operation_id = getUUIDPrimaryKey();
		
		Map<String, Object> signmap = new HashMap<String, Object>();
		signmap.put("count", 1);
		signmap.put("operation_id", operation_id);
		String signstr = signRequest(AvataConfig.ACCOUNTS,null,signmap,Long.parseLong(timestamp),avata_api_secret);
		
		
		Map<String, String> params = new HashMap<String, String>();
		params.put("count", "1");
		params.put("operation_id", operation_id);
		params.put("X-Api-Key", avata_api_key);
		params.put("X-Signature", signstr);
		params.put("X-Timestamp", timestamp);
		System.out.println("sign:"+ signstr);
		String result = httpPost(path, params);
		System.err.println(result);
	}
	
	/**
	 * 执行HttpPost请求
	 * @param url 请求路径
	 * @param params 参数
	 * @return 结果
	 */
	public static String httpPost(String url, Map<String, String> params){
		CloseableHttpClient httpClient = HttpClients.createDefault();
		HttpPost httpPost =   new HttpPost(url);
		CloseableHttpResponse response = null;
		String result = null;
		try {
			List<NameValuePair> nameValuePairs = new ArrayList<NameValuePair>();
			if (null != params && params.size() > 0) {
				for (Map.Entry<String, String> entry : params.entrySet()) {
					String key = entry.getKey();
					String value = entry.getValue();
					if (key == null || value == null) {
						continue;
					}
					NameValuePair pair = new BasicNameValuePair(key, value);
					nameValuePairs.add(pair);
				}
			}
			httpPost.setEntity(new UrlEncodedFormEntity(nameValuePairs,"UTF-8"));
			httpPost.setHeader("Content-type", "application/json");
			httpPost.setHeader("X-Api-Key", params.get("X-Api-Key"));
			httpPost.setHeader("X-Signature", params.get("X-Signature"));
			httpPost.setHeader("X-Timestamp", params.get("X-Timestamp"));
			// 执行请求
			response = httpClient.execute(httpPost);
			HttpEntity entity = response.getEntity();
			if (null != entity) {
				result = EntityUtils.toString(entity, "UTF-8");
				EntityUtils.consume(entity);
			}
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				if (response != null) {
					response.close();
				}
			} catch (IOException e) {
				e.printStackTrace();
				System.out.println("请求通信[\" + reqURL + \"]时网络时，关闭异常,堆栈轨迹如下");
			}
			httpPost.releaseConnection();
		}
		return result;
	}
public static String signRequest(String path, Map<String, Object> query, Map<String, Object> body, long timestamp, String apiSecret) {
        Map<String, Object> paramsMap = new HashMap();

        paramsMap.put("path_url", path);

        if (query != null && !query.isEmpty()) {
//            query.forEach((key, value) -> paramsMap.put("query_" + key, value));
        	String key = "";
        	Object value = "";
            for(Map.Entry<String, Object> entry : query.entrySet()){
            	key = entry.getKey();
            	value = entry.getValue();
                paramsMap.put("query_" + key, value);
            }
        }

        if (body != null && !body.isEmpty()) {
//            body.forEach((key, value) -> paramsMap.put("body_" + key, value));
            String key = "";
        	Object value = "";
            for(Map.Entry<String, Object> entry : body.entrySet()){
            	key = entry.getKey();
            	value = entry.getValue();
                paramsMap.put("body_" + key, value);
            }
        }

        // 将请求参数序列化为排序后的 JSON 字符串
        String jsonStr = JSON.toJSONString(paramsMap);

        // 执行签名
        String signature = sha256Sum(jsonStr + String.valueOf(timestamp) + apiSecret);

        return signature;
    }


然后我又将请求参数序列化为排序后的 JSON 字符串 String jsonStr = JSON.toJSONString(paramsMap, SerializerFeature.MapSortField); 序列化时传入了一个排序参数
然后又报错了
java.io.IOException: Server returned HTTP response code: 403 for URL: https://stage.apis.avata.bianjie.ai/v1beta1/accounts
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
at com.perssoft.avata.HttpPostJson.sendPost(HttpPostJson.java:61)
at com.perssoft.avata.AvataUtils.main(AvataUtils.java:49)

**Comment by MaricoHan** [comment]
@BAige88 你好，这个issue已经关闭了，可以重新创建一个issue，会有技术人员定期关注问题，另外麻烦把代码格式化一下，这样技术人员可以更快速排查出问题。
