### ISSUE TITLE
代付手续费功能怎么使用？

### ISSUE THREAD

**Issue by brom15** [bianjieai/opb-faq#31]
opb-sdk-java 0.1.10-rc版本中的添加的代付手续费功能怎么使用？
feeGranter，feePayer 分别填什么值。能否提供一个实例。

**Comment by zhangyelong** [comment]
代付手续费只需要填写 feeGranter 的地址，值就是 iaa 开头的授权者的链账户地址。
但使用代付功能的前提是，授权者给被授权者执行授权，然后被授权者构造交易时指定 feeGranter 的地址，并使用自己的私钥签名。

**Comment by zhangyelong** [comment]
OPB SDK 里暂时没有开放授权操作，我们安排一下，但可能需要一些时间。

**Comment by 17y** [comment]
这个功能可以提高优先级吗 急需！

**Comment by sin3A** [comment]
> 这个功能可以提高优先级吗 急需！

下周一前可以提供

**Comment by 17y** [comment]
> 提供

👍👍👍

**Comment by sin3A** [comment]
> > 提供
> 
> 👍👍👍

https://github.com/bianjieai/opb-sdk-java/pull/65

**Comment by prolenking** [comment]
@17y opb-sdk-java已于[v0.1.11](https://github.com/bianjieai/opb-sdk-java/releases/tag/v0.1.11)中增加feegrant的相关功能

**Comment by 17y** [comment]
> @17y opb-sdk-java已于[v0.1.11](https://github.com/bianjieai/opb-sdk-java/releases/tag/v0.1.11)中增加feegrant的相关功能

我们现在用的是opb-sdk-go，请问有更新计划吗- -

**Comment by junjie-bianjie** [comment]
java-sdk可以参考README.md和FeeGrantTest.java
