### ISSUE TITLE
文昌链可以通过 hardhat 执行 solidity 合约吗？

### ISSUE THREAD

**Issue by romejiang** [bianjieai/opb-faq#33]
在文昌链上执行solidity 有没有类似的经验或文档，谢谢了[握手]

**Comment by zhangyelong** [comment]
没问题，以太坊生态的工具基本全部兼容，如果使用过程中遇到问题欢迎反馈

**Comment by BAige88** [comment]
创建链账户时报错
{"error":{"code_space":"ACCOUNTS","code":"INTERNAL_ERROR","message":"internal error"}}
