### ISSUE TITLE
上链不稳定，请给予帮助

### ISSUE THREAD

**Issue by git-guang** [bianjieai/opb-faq#37]
`<?php

namespace app\api\controller;

use think\Db;
use think\cache\driver\Redis;
use app\common\library\Auth;
use es\ElasticSearch;
use app\common\controller\Esearch;
use think\Exception;
use think\Model;

/**
 * 定时任务
 */
class Timedtask
{

    /**
     * 作品上链
     * 计划任务URL http://xxxxxxx
     */
    public function setNfts(){
        $model=new \app\admin\model\Works();
        $result = $model->with(['worksimages','worksvideo','worksf3d']);
        $result=$result->field('id,type_id,type_name,title,original_user');
        $result=$result->where('avata_task_id',0);
        $result=$result->where('softdel_time',0);
        $result=$result->where('is_weigui',0);
        $result=$result->where('valid',1);
        $result=$result->where('status',1);
        $result=$result->group('original_user');
        $result=$result->limit(1);
        $result=$result->orderRaw('rand()');
        $result=$result->select();
        //exit ($result->fetchSql()->select());
        $result = collection($result)->toArray();
        if(empty($result[0]['id'])) exit('暂无可处理的数据！');
        //print_r($result);die;
        //获取NFT类别
        //$classes = \app\common\library\AvataAPI::instance()->getClasses([]);
        $classes=[
            'images'=>'xxxxxxx',
            'video'=>'xxxxxx',
            'f3d'=>'xxxxxx'
        ];
        $c=[
            '2'=>[
                'id'=>$classes['images'],
                'name'=>'images',
                'ext_filed'=>'worksimages',
                'ext_val'=>'images'
            ],
            '4'=>[
                'id'=>$classes['video'],
                'name'=>'video',
                'ext_filed'=>'worksvideo',
                'ext_val'=>'video'
            ],
            '5'=>[
                'id'=>$classes['f3d'],
                'name'=>'f3d',
                'ext_filed'=>'worksf3d',
                'ext_val'=>'f3d'
            ]
        ];
        //if(empty($classes['data']['classes'])) exit('未设置NFT类别！');
        //$c=[];
        // foreach ($classes['data']['classes'] as $v){
        //   if($v['name'] == 'txt') {
        //       $c[1]=$v;
        //   }else if($v['name'] == 'image') {//图片
        //       $v['ext_filed']='worksimages';
        //       $v['ext_val']='images';
        //       $c[2]=$v;
        //   }else if($v['name'] == 'audio') {
        //       $c[3]=$v;
        //   }else if($v['name'] == 'worksvideo') {//视频
        //       $v['ext_filed']='worksvideo';
        //       $v['ext_val']='video';
        //       $c[4]=$v;
        //   }else if($v['name'] == 'three-D') { //3d
        //       $v['ext_filed']='worksf3d';
        //       $v['ext_val']='f3d';
        //       $c[5]=$v;
        //   }
        // }
        //发行NFT
        foreach ($result as $k=>$v){
            if(empty($c[$v['type_id']])) continue;
            $field_ext=!empty($c[$v['type_id']]['ext_filed']) ? $c[$v['type_id']]['ext_filed'] : '';
            $ext_val=!empty($c[$v['type_id']]['ext_val']) ? $c[$v['type_id']]['ext_val'] : '';
            $uri=!empty($v[$field_ext][$ext_val]) ? $v[$field_ext][$ext_val] : '';
            $query=[
                'class_id'=>$c[$v['type_id']]['id'] //[必填]NFT类别ID
            ];
            //标题转拼音
            $name=\app\common\library\Pinyin::instance()->strChange($v['title']);
            $name = substr($name, 0, 64);
            $body=[
                'name'=>$name,//[必填]NFT 名称
                'uri'=>$uri ? 'https://xxxxxxxxxxx.aliyuncs.com'.$uri : '',//[选填]链外数据链接
                'uri_hash'=>'', //[选填]链外数据 Hash
                'data'=>urlencode(''),//[选填]自定义链上元数据
                //'recipient'=>(string)$avata_accounts,//[选填]NFT 接收者地址，默认为 NFT 类别的权属者地址
                'recipient'=>'',//[选填]NFT 接收者地址，默认为 NFT 类别的权属者地址
                'operation_id'=>(string)$v['original_user'].'_'.$v['id'],//[必填]操作 ID
            ];
            
            $res = \app\common\library\AvataAPI::instance()->addFfts($query,$body);
            print_r($res);
            if(!empty($res['data']['task_id'])){
                sleep(10);
                $tx = \app\common\library\AvataAPI::instance()->txTask(['task_id'=>$res['data']['task_id']]);
                //print_r($tx);
                $update=['avata_task_id'=>$res['data']['task_id'],'avata_hash'=>$tx['data']['tx_hash']];
                \think\Db::name('works')->where('id',$v['id'])->update($update);
            }else{
                #...记录日志
                //continue;
            }
            
            echo (!empty($res['data']['task_id']) ? '上链成功HASH：['.$tx['data']['tx_hash'].']': $res['msg']).'<br/>';
            print_r($body);
        }
    }
    

}
`
`<?php
namespace app\common\library;
/** Avata 文昌链接口
 *  测试查询：http://58.33.6.114:28000/
 * Class AvataAPI
 */
class AvataAPI{
    /**接口APP KEY
     * @var string
     */
    private $apiKey = "xxxxxxxxx";
    /**接口APP Secret
     * @var string
     */
    private $apiSecret = "xxxxxxxxxx";
    /**API 网关
     * 生产网关 https://apis.avata.bianjie.ai
     * 测试网关 https://stage.apis.avata.bianjie.ai/
     * @var string
     */
    private $apiGateway='https://stage.apis.avata.bianjie.ai/';
    /**单例模式
     * @var
     */
    private static $_instance;
    /**错误码
     * @var string[]
     */
    private $code=[
        'INTERNAL_ERROR'=>'内部服务错误',
        'NOT_FOUND'=>'访问信息不存在或暂时查询不到',
        'FORBIDDEN'=>'无访问权限',
        'PARAMS_ERROR'=>'参数错误',
        'FREQUENT_REQUESTS_NOT_SUPPORTS'=>'暂不支持频繁请求',
        'NFT_CLASS_STATUS_ABNORMAL'=>'NFT 类别状态异常',
        'NFT_STATUS_ABNORMAL'=>'NFT 状态异常',
    ];

    /**不可实例化
     * AvataAPI constructor.
     */
    private function __construct()
    {
    }

    /**入口
     * @return AvataAPI
     */
    public static function instance(){
       if(empty(self::$_instance)) self::$_instance=new self();
       return self::$_instance;
    }

    /**创建帐户
     * @param array $body
     * @return array
     * $body=['count'=>1,'operation_id'=>123456]
     */
    public function createAccount(array $body):array{
       return $this->apiGet('/v1beta1/accounts',[],$body,'POST');
    }

    /**查询帐户
     * @param array $query
     * @return array
     */
    public function getAccount(array $query):array{
        return $this->apiGet('/v1beta1/accounts',$query,[],'GET');
    }

    /**查询链账户操作记录
     * @param array $query
     * @return array|bool|string
     */
    public function getAccountHistory(array $query){
        return $this->apiGet('/v1beta1/accounts/history',$query,[],'GET');
    }

    /**上链结果查询
     * @param array $query
     * @return array
     */
    public function txTask(array $query):array{
        return $this->apiGet('/v1beta1/tx/'.$query['task_id'],[],[],'GET');
    }

    /**创建 NFT 类别
     * @param $body
     * @return array
     */
    public function createClasses(array $body):array{
        return $this->apiGet('/v1beta1/nft/classes',[],$body,'POST');
    }

    /**查询 NFT 类别
     * @param array $query
     * @return array
     */
    public function getClasses(array $query):array{
        $result = $this->apiGet('/v1beta1/nft/classes',$query,[],'GET');
        if(!empty($result['data']['classes'])){
           foreach ($result['data']['classes'] as $k=>&$v) {
               $v['name']=urldecode($v['name']);
               if(array_key_exists('description',$v)) $v['description']=urldecode($v['description']);
               if(array_key_exists('uri_hash',$v)) $v['uri_hash']=urldecode($v['uri_hash']);
               if(array_key_exists('uri',$v)) $v['uri']=urldecode($v['uri']);
               if(array_key_exists('symbol',$v)) $v['symbol']=urldecode($v['symbol']);
           }
        }
        return $result;
    }

    /**查询 NFT 类别详情
     * @param array $query
     * @return array
     */
    public function getClassesDetails(array $query):array{
        $result = $this->apiGet('/v1beta1/nft/classes/'.$query['id'],[],[],'GET');
        if(!empty($result['data']['id'])){
            $result['data']['name']=urldecode($result['data']['name']);
            $result['data']['description']=urldecode($result['data']['description']);
            $result['data']['uri_hash']=urldecode($result['data']['uri_hash']);
            $result['data']['uri']=urldecode($result['data']['uri']);
            $result['data']['symbol']=urldecode($result['data']['symbol']);
        }
        return $result;
    }

    /**转让 NFT 类别
     * @param array $query
     * @return array
     */
    public function classTransfers(array $query,array $body):array{
        return $this->apiGet("/v1beta1/nft/class-transfers/{$query['class_id']}/{$query['owner']}",[],$body,'POST');
    }

    /**发行 NFT
     * @param array $query
     * @param array $body
     * @return array
     */
    public function addFfts(array $query,array $body):array{
        return $this->apiGet("/v1beta1/nft/nfts/{$query['class_id']}",[],$body,'POST');
    }

    /**查询 NFT
     * @param array $query
     * @return array
     */
    public function getNftsList(array $query):array{
        $result = $this->apiGet("/v1beta1/nft/nfts",$query,[],'GET');
        if(!empty($result['data']['nfts'])){
            foreach ($result['data']['nfts'] as $k=>&$v){
                $v['name']=urldecode($v['name']);
                $v['class_name']=urldecode($v['class_name']);
                $v['class_symbol']=urldecode($v['class_symbol']);
                $v['uri']=urldecode($v['uri']);
            }
        }
        return $result;
    }

    /**查询 NFT 详情
     * @param array $query
     * @return array
     */
    public function getNftsDetails(array $query):array{
        $result = $this->apiGet("/v1beta1/nft/nfts/{$query['class_id']}/{$query['nft_id']}",[],[],'GET');
        if(!empty($result['data'])){
            $result['data']['name']=urldecode($result['data']['name']);
            $result['data']['class_name']=urldecode($result['data']['class_name']);
            $result['data']['class_symbol']=urldecode($result['data']['class_symbol']);
            $result['data']['data']=urldecode($result['data']['data']);
            $result['data']['uri']=urldecode($result['data']['uri']);
            $result['data']['uri_hash']=urldecode($result['data']['uri_hash']);
        }
        return $result;
    }

    /**查询 NFT 操作记录
     * @param array $path_param
     * @param array $query
     * @return array
     */
    public function getNftsHistory(array $path_param,array $query):array{
        $result = $this->apiGet("/v1beta1/nft/nfts/{$path_param['class_id']}/{$path_param['nft_id']}/history",$query,[],'GET');
        return $result;
    }

    /**销毁 NFT
     * @param array $path_param
     * @return array
     */
    public function nftsStroy(array $path_param):array{
        $result = $this->apiGet("/v1beta1/nft/nfts/{$path_param['class_id']}/{$path_param['owner']}/{$path_param['nft_id']}",[],[],'DELETE');
        return $result;
    }

    /**编辑 NFT
     * @param array $path_param
     * @param array $body
     * @return array
     */
    public function nftsUpdate(array $path_param,array $body):array{
        $result = $this->apiGet("/v1beta1/nft/nfts/{$path_param['class_id']}/{$path_param['owner']}/{$path_param['nft_id']}",[],$body,'PATCH');
        return $result;
    }

    /**转让 NFT
     * @param array $path_param
     * @param array $body
     * @return array
     */
    public function transferFfts(array $path_param,array $body):array{
        $result = $this->apiGet("/v1beta1/nft/nft-transfers/{$path_param['class_id']}/{$path_param['owner']}/{$path_param['nft_id']}",[],$body,'POST');
        return $result;
    }

    /**CURL 获取
     * @param string $path
     * @param array $query
     * @param array $body
     * @param string $method
     * @return bool|string
     */
    private function apiGet(string $path,array $query=[],array $body=[],string $method='GET'){
        $method=strtoupper($method);
        $apiGateway=rtrim($this->apiGateway,'/').'/'.ltrim($path,'/').($query ? '?'.http_build_query($query) : '');
        $timestamp = $this->getMillisecond();
        $params = ["path_url" => $path];
        if($query) foreach ($query as $k=>$v) $params["query_{$k}"]=$v;
        if($body) foreach ($body as $k=>$v) $params["body_{$k}"] = $v;
        ksort($params);
        $hexHash = hash("sha256", "{$timestamp}" . $this->apiSecret);
        if (count($params) > 0) {
            $s = json_encode($params);
            $hexHash = hash("sha256", stripcslashes($s . "{$timestamp}" . $this->apiSecret));
        }
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $apiGateway);
        $header=[
            "Content-Type:application/json",
            "X-Api-Key:{$this->apiKey}",
            "X-Signature:{$hexHash}",
            "X-Timestamp:{$timestamp}"
        ];
        curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
        $jsonStr =$body ? json_encode($body) : ''; //转换为json格式
        //print_r($jsonStr);die;
        if($method == 'POST'){
            curl_setopt($ch, CURLOPT_POST, 1);
            if($jsonStr) curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonStr);
        }else if($method == 'PATCH'){
            curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PATCH');
            if($jsonStr) curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonStr);
        }else if($method == 'PUT'){
            curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
            if($jsonStr) curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonStr);
        }else if($method == 'DELETE'){
            curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'DELETE');
            if($jsonStr) curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonStr);
        }
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);
        $response=json_decode($response,true);
        if($httpCode == 200) return ['code'=>200,'msg'=>'ok','data'=>$response['data']];
        $code=!empty($response['error']['code']) ? $response['error']['code'] : '-1000';
        $msg=!empty($this->code[$code]) ? $this->code[$code] : '未知错误';
        return ['code'=>$httpCode,'msg'=>"{$code} ".$msg,'data'=>[]];
    }

    /**获取毫秒时间戳
     * @return float
     */
    private function getMillisecond(){
        list($t1, $t2) = explode(' ', microtime());
        return (float)sprintf('%.0f', (floatval($t1) + floatval($t2)) * 1000);
    }
}`

**Comment by zhangyelong** [comment]
是否方便格式化一下

**Comment by zhangyelong** [comment]
> 'operation_id'=>(string)$v['original_user'].'_'.$v['id'],//[必填]操作 ID

这个是用户 ID 吗

**Comment by git-guang** [comment]
> > 'operation_id'=>(string)$v['original_user'].'_'.$v['id'],//[必填]操作ID
> 
> 这个是用户ID吗
对

**Comment by zhangyelong** [comment]
这个是不对的，Operation ID 是「操作」 ID，不是「操作者」ID，针对每个请求要独一无二，否则就会被服务器拦截，以保障幂等性，避免由于网络异常等原因，客户端重试导致超发。参考 API 文档：https://apis.avata.bianjie.ai
<img width="629" alt="image" src="https://user-images.githubusercontent.com/31681438/167356733-b6fabfd8-6d46-4762-a246-4646f1eb4019.png">

**Comment by git-guang** [comment]
> 这是不正确的，操作 ID 是保障操作 ID，不是“操作者”ID，针对每个人要求“表示，否则会被服务器拦截，以主动性等，避免网络异常等原因，客户端重试文档导致超发。参考API：[https ://apis.avata.bianjie.ai](https://apis.avata.bianjie.ai) <img alt="图片" width="629" src="https://user-images.githubusercontent.com/31681438/167356733-b6fabfd8-6d46-4762-a246-4646f1eb4019.png">

![image](https://user-images.githubusercontent.com/32994599/167356971-d3e6d201-5779-4b4a-99f2-c7acd12d9e56.png)
ID主键是唯一的

**Comment by zhangyelong** [comment]
是针对用户唯一，还是针对每次请求唯一？
比如一个用户，请求多次 API，这个 ID 是不变的吗？

**Comment by git-guang** [comment]
> 是针对用户唯一，还是针对每次请求唯一？ 比如一个用户，请求多次 API，这个 ID 是不变的吗？

每次请求唯一

**Comment by unionstep** [comment]
FORBIDDEN 无访问权限<br/>Array
(
    [name] => WeiLaiZhiCheng-WeiLai1Hao100/100	
    [uri] => https://qjft.oss-cn-guangzhou.aliyuncs.com/uploads/20211226/975ff442644946b6409235a8ca38f81e.mp4
    [uri_hash] => 
    [data] => 
    [recipient] => 
    [operation_id] => 10237_17190_1652086722
)

在访问的时候，经常出现Array ( [code] => 403 [msg] => FORBIDDEN 无访问权限 [data] => Array ( ) )

**Comment by zhangyelong** [comment]
> > 是针对用户唯一，还是针对每次请求唯一？ 比如一个用户，请求多次 API，这个 ID 是不变的吗？
> 
> 每次请求唯一

在 API 响应的内容中，除了返回「错误码」，还返回了「错误描述」，是否可以把错误描述打印出来看一下：
```json
{
    "error": {
        "code_space": "命名空间",
        "code": "错误码",
        "message": "错误描述"
    }
}
```

**Comment by unionstep** [comment]
> > > 是针对用户唯一，还是针对每次请求唯一？ 比如一个用户，请求多次 API，这个 ID 是不变的吗？
> > 
> > 
> > 每次请求唯一
> 
> 在 API 响应的内容中，除了返回「错误码」，还返回了「错误描述」，是否可以把错误描述打印出来看一下：
> 
> ```json
> {
>     "error": {
>         "code_space": "命名空间",
>         "code": "错误码",
>         "message": "错误描述"
>     }
> }
> ```


Array
--
  | (
  | [code] => 403
  | [msg] => FORBIDDEN 无访问权限
  | [data] => Array
  | (
  | )
  |  
  | )



Array
--
  | (
  | [code] => 403
  | [msg] => FORBIDDEN 无访问权限
  | [data] => Array
  | (
  | )
  |  
  | )

**Comment by zhangyelong** [comment]
这个是你们转换之后的，不是原始结构。
那我们先排查一下 `FORBIDDEN` 的问题，请提供一个完整的请求参数（能够 100% 复现 403 的请求），包括请求头（Header）、请求体（JSON Body）、URI 和 Query 参数，便于我们用同样参数构造签名进行比对

**Comment by zhangyelong** [comment]
> > > 是针对用户唯一，还是针对每次请求唯一？ 比如一个用户，请求多次 API，这个 ID 是不变的吗？
> > 
> > 
> > 每次请求唯一
> 
> 在 API 响应的内容中，除了返回「错误码」，还返回了「错误描述」，是否可以把错误描述打印出来看一下：
> 
> ```json
> {
>     "error": {
>         "code_space": "命名空间",
>         "code": "错误码",
>         "message": "错误描述"
>     }
> }
> ```

对于 `FREQUENT_REQUESTS_NOT_SUPPORTS` 的问题，麻烦把返回的 JSON 中 `error` 里面的 `message` 打印出来看一下

**Comment by unionstep** [comment]
{"error":{"code_space":"NFTP-OPEN-API","code":"FORBIDDEN","message":"authentication failed"}}Array
--
  | (
  | [code] => 403
  | [msg] => FORBIDDEN 无访问权限
  | [data] => Array
  | (
  | )
  |  
  | )

**Comment by unionstep** [comment]
{"error":{"code_space":"NFTP-OPEN-API","code":"FORBIDDEN","message":"authentication failed"}}Array
--
  | (
  | [code] => 403
  | [msg] => FORBIDDEN 无访问权限
  | [data] => Array
  | (
  | )
  |  
  | )

**Comment by unionstep** [comment]
{"error":{"code_space":"NFTP-OPEN-API","code":"FORBIDDEN","message":"authentication failed"}}Array
--
  | (
  | [code] => 403
  | [msg] => FORBIDDEN 无访问权限
  | [data] => Array
  | (
  | )
  |  
  | )

**Comment by unionstep** [comment]
> > > > 是针对用户唯一，还是针对每次请求唯一？ 比如一个用户，请求多次 API，这个 ID 是不变的吗？
> > > 
> > > 
> > > 每次请求唯一
> > 
> > 
> > 在 API 响应的内容中，除了返回「错误码」，还返回了「错误描述」，是否可以把错误描述打印出来看一下：
> > ```json
> > {
> >     "error": {
> >         "code_space": "命名空间",
> >         "code": "错误码",
> >         "message": "错误描述"
> >     }
> > }
> > ```
> 
> 对于 `FREQUENT_REQUESTS_NOT_SUPPORTS` 的问题，麻烦把返回的 JSON 中 `error` 里面的 `message` 打印出来看一下



{"error":{"code_space":"NFTP-OPEN-API","code":"FORBIDDEN","message":"authentication failed"}}Array
--
  | (
  | [code] => 403
  | [msg] => FORBIDDEN 无访问权限
  | [data] => Array
  | (
  | )
  |  
  | )

**Comment by zhangyelong** [comment]
现在是有两个问题，请分别按以下方式操作：
### FORBIDDEN 的问题
请提供一个完整的请求参数（能够 100% 复现 403 的请求），包括请求头（Header）、请求体（JSON Body）、URI 和 Query 参数，便于我们用同样参数构造签名进行比对

### FREQUENT_REQUESTS_NOT_SUPPORTS 的问题
请把返回的 JSON 中 error 里面的 message 打印出来看一下

**Comment by zhangyelong** [comment]
### 关于 FREQUENT_REQUESTS_NOT_SUPPORTS 的问题

可以用以下 CURL 命令行测试：
```bash
curl --location --request POST 'https://stage.apis.avata.bianjie.ai/v1beta1/nft/nfts/nftp1aa9e96430620f3e673a7be898ca38335d618e9ab9897a4357a102b5036890e1' \
--header 'Content-Type: application/json' \
--header 'X-Api-Key: dAuB90yF9Wi6PY59nr4R7mvY2ngiWBC' \
--header 'X-Timestamp: 1651742524207' \
--header 'X-Signature: 5e81a490688ac4f350ccbe828021022428771ec6760eaa22e7eda5230f050928' \
--data-raw '{
    "name": "NFT 测试",
    "recipient": "iaa1p0xvrw027zulacv67awr2cdw625x2h0tym2ntg",
    "operation_id": "001"
}'
```
**注意：**

1. 第一次应执行成功，返回类似如下的 task_id：
    ```json
     {"data":{"task_id":"9D4A0A221DD76954643812DBE9C94B8D35E377C21C1817E8378CDED8A2446011"}}
    ```
2. 立即执行第二次，就会报错 `FREQUENT_REQUESTS_NOT_SUPPORTS`，详细的错误信息是：
    ```json
    {"error":{"code_space":"NFTP-OPEN-API","code":"FREQUENT_REQUESTS_NOT_SUPPORTS","message":"duplicate request, operation_id: 001"}}
    ```

因为使用相同的 operation id 重复请求，会被拦截

**Comment by unionstep** [comment]
> 现在是有两个问题，请【**分别**】按以下方式操作：
> 
> ### FORBIDDEN 的问题
> 请提供一个完整的请求参数（能够 100% 复现 403 的请求），包括请求头（Header）、请求体（JSON Body）、URI 和 Query 参数，便于我们用同样参数构造签名进行比对
> 
> ### FREQUENT_REQUESTS_NOT_SUPPORTS 的问题
> 请把返回的 JSON 中 error 里面的 message 打印出来看一下



  | https://apis.avata.bianjie.ai/v1beta1/nft/nfts/nftpcff360950e7726d38d0c02c3d6f933c3ca6e8db1fb52f95bfcb5e4c486cf8ac9<br>Array
-- | --
  | (
  | [0] => Content-Type:application/json
  | [1] => X-Api-Key:o1MB79qN8k6twwc6fMnUJsv1SskMO7oL
  | [2] => X-Signature:7cfdd3018f64454fc69ef334be6de4f73f1731f2b14bc2dbc6af5a734b93eb7d
  | [3] => X-Timestamp:1652107976814
  | )
  | <br>{"name":"WeiLaiZhiCheng-WeiLai1Hao100\/100\t","uri":"https:\/\/qjft.oss-cn-guangzhou.aliyuncs.com\/uploads\/20211226\/975ff442644946b6409235a8ca38f81e.mp4","uri_hash":"","data":"","recipient":"","operation_id":"10237_17190_1652107976"}<br>{"error":{"code_space":"NFTP-OPEN-API","code":"FORBIDDEN","message":"authentication failed"}}Array
  | (
  | [code] => 403
  | [msg] => FORBIDDEN 无访问权限
  | [data] => Array
  | (
  | )
  |  
  | )
  | FORBIDDEN 无访问权限<br/>Array
  | (
  | [name] => WeiLaiZhiCheng-WeiLai1Hao100/100
  | [uri] => https://qjft.oss-cn-guangzhou.aliyuncs.com/uploads/20211226/975ff442644946b6409235a8ca38f81e.mp4
  | [uri_hash] =>
  | [data] =>
  | [recipient] =>
  | [operation_id] => 10237_17190_1652107976
  | )
  |

**Comment by wangjiulian** [comment]
> FORBIDDEN

![image](https://user-images.githubusercontent.com/8965798/167530286-3dbb8745-4007-475f-a0d2-02a861ffcfd1.png)
签名前序列化这块，修改成这个   $s = json_encode($params,JSON_UNESCAPED_UNICODE); 现在包含中文名可能鉴权失败

**Comment by unionstep** [comment]
> 
换成你这种写法，仍然没有啥效果。

**Comment by wangjiulian** [comment]
> 

就是同样的方法去请求，有成功也有失败 是这样吗

**Comment by unionstep** [comment]
> > 
> 
> 就是同样的方法去请求，有成功也有失败 是这样吗

是的。

**Comment by wangjiulian** [comment]
<?php

$apiKey = "o1MB79qN8k6twwc6fMnUJsv1SskMO7oL";
$apiSecret = "xxxxxxxxxx";//替换成自己的
$domain = "http://apis.avata.bianjie.ai";//域名
$path = "/v1beta1/nft/nfts/nftpcff360950e7726d38d0c02c3d6f933c3ca6e8d";//接口路径
$body = [
    "name" => "WeiLaiZhiCheng-WeiLai1Hao100/100",
    "uri" => "https://qjft.oss-cn-guangzhou.aliyuncs.com/uploads/20211226/975ff442644946b6409235a8ca38f81e.mp4",
    "uri_hash" => "",
    "data" => "",
    "recipient" => "",
    "operation_id" => "10237_17190_1652107976",

];
$query = [];
$timestamp = 1652107976814;
$params = ["path_url" => $path];
if ($query) {
    foreach ($query as $k => $v) {
        $params["query_{$k}"] = $v;
    }
}
if ($body) {
    foreach ($body as $k => $v) {
        $params["body_{$k}"] = $v;
    }
}
ksort($params);
$hexHash = hash("sha256", "{$timestamp}" . $apiSecret);
if (count($params) > 0) {
    $s = json_encode($params);
    $hexHash = hash("sha256", stripcslashes($s . "{$timestamp}" . $apiSecret));
}

echo "X-Api-Key:{$apiKey}" . PHP_EOL;
echo "X-Signature:{$hexHash}" . PHP_EOL;
echo "X-Timestamp:{$timestamp}" . PHP_EOL;
?>

针对这条有问题的记录，本地运行的签名和你不一致。可以确认下
X-Api-Key:o1MB79qN8k6twwc6fMnUJsv1SskMO7oL
X-Signature:8fd6e6f454f4d23b4bb6573d95c57757ad94c6540254e1b61c25342194314b6f
X-Timestamp:1652107976814

**Comment by wangjiulian** [comment]
> > 现在是有两个问题，请【**分别**】按以下方式操作：
> > ### FORBIDDEN 的问题
> > 请提供一个完整的请求参数（能够 100% 复现 403 的请求），包括请求头（Header）、请求体（JSON Body）、URI 和 Query 参数，便于我们用同样参数构造签名进行比对
> > ### FREQUENT_REQUESTS_NOT_SUPPORTS 的问题
> > 请把返回的 JSON 中 error 里面的 message 打印出来看一下
> 
>  	https://apis.avata.bianjie.ai/v1beta1/nft/nfts/nftpcff360950e7726d38d0c02c3d6f933c3ca6e8db1fb52f95bfcb5e4c486cf8ac9
> Array
>  	(
>  	[0] => Content-Type:application/json
>  	[1] => X-Api-Key:o1MB79qN8k6twwc6fMnUJsv1SskMO7oL
>  	[2] => X-Signature:7cfdd3018f64454fc69ef334be6de4f73f1731f2b14bc2dbc6af5a734b93eb7d
>  	[3] => X-Timestamp:1652107976814
>  	)
>  	
> {"name":"WeiLaiZhiCheng-WeiLai1Hao100/100\t","uri":"https://qjft.oss-cn-guangzhou.aliyuncs.com/uploads/20211226/975ff442644946b6409235a8ca38f81e.mp4","uri_hash":"","data":"","recipient":"","operation_id":"10237_17190_1652107976"}
> {"error":{"code_space":"NFTP-OPEN-API","code":"FORBIDDEN","message":"authentication failed"}}Array
>  	(
>  	[code] => 403
>  	[msg] => FORBIDDEN 无访问权限
>  	[data] => Array
>  	(
>  	)
>  	 
>  	)
>  	FORBIDDEN 无访问权限
> Array
>  	(
>  	[name] => WeiLaiZhiCheng-WeiLai1Hao100/100
>  	[uri] => https://qjft.oss-cn-guangzhou.aliyuncs.com/uploads/20211226/975ff442644946b6409235a8ca38f81e.mp4
>  	[uri_hash] =>
>  	[data] =>
>  	[recipient] =>
>  	[operation_id] => 10237_17190_1652107976
>  	)

****

<?php

$apiKey = "o1MB79qN8k6twwc6fMnUJsv1SskMO7oL";
$apiSecret = ["xxxxxxxxxx";//替换成自己的](url)
$domain = "http://apis.avata.bianjie.ai";//域名
$path = "/v1beta1/nft/nfts/nftpcff360950e7726d38d0c02c3d6f933c3ca6e8d";//接口路径
$body = [
    "name" => "WeiLaiZhiCheng-WeiLai1Hao100/100",
    "uri" => "https://qjft.oss-cn-guangzhou.aliyuncs.com/uploads/20211226/975ff442644946b6409235a8ca38f81e.mp4",
    "uri_hash" => "",
    "data" => "",
    "recipient" => "",
    "operation_id" => "10237_17190_1652107976",

];
$query = [];
$timestamp = 1652107976814;
$params = ["path_url" => $path];
if ($query) {
    foreach ($query as $k => $v) {
        $params["query_{$k}"] = $v;
    }
}
if ($body) {
    foreach ($body as $k => $v) {
        $params["body_{$k}"] = $v;
    }
}
ksort($params);
$hexHash = hash("sha256", "{$timestamp}" . $apiSecret);
if (count($params) > 0) {
    $s = json_encode($params);
    $hexHash = hash("sha256", stripcslashes($s . "{$timestamp}" . $apiSecret));
}

echo "X-Api-Key:{$apiKey}" . PHP_EOL;
echo "X-Signature:{$hexHash}" . PHP_EOL;
echo "X-Timestamp:{$timestamp}" . PHP_EOL;
?>

针对这条有问题的记录，本地运行的签名和你不一致。可以确认下
X-Api-Key:o1MB79qN8k6twwc6fMnUJsv1SskMO7oL
X-Signature:8fd6e6f454f4d23b4bb6573d95c57757ad94c6540254e1b61c25342194314b6f
X-Timestamp:1652107976814

**Comment by BAige88** [comment]
创建链账户时报错
{"error":{"code_space":"ACCOUNTS","code":"INTERNAL_ERROR","message":"internal error"}}
