### ISSUE TITLE
创建账户失败，提示module is invalid, 请给予帮助

### ISSUE THREAD

**Issue by eininst** [bianjieai/opb-faq#38]
请求地址, POST: https://stage.apis.avata.bianjie.ai/v1beta1/accounts
返回数据:  {"error":{"code_space":"ACCOUNTS","code":"MODULE_ERROR","message":"module is invalid"}}

我按照文档请求你们接口, 返回module is invalid 是什么问题 

request header:  {"Content-Type":["accept: application/json"],"X-Api-Key":["YkYldszIi1E3qPlIDnvWuyvIsuXAf7x"],"X-Signature":["4ed0281c27f2090091937cff96385a395d705098197bb00a5f0f03d6f0a742e0"],"X-Timestamp":["1652084134000"]}

request body: {"count":1,"operation_id":"3923845a3db84c9fa58e7cf6e0b52615"}

**Comment by zhangyelong** [comment]
抱歉我这边没试出来，请问现在还是一样的报错吗
<img width="632" alt="image" src="https://user-images.githubusercontent.com/31681438/167435111-8806b23b-46ab-4a7e-97d9-a9afbc027a4f.png">
