### ISSUE TITLE
创建NFT失败

### ISSUE THREAD

**Issue by akak774** [bianjieai/opb-faq#45]
之前一直好着，从前两天开始不能创建NFT了，这是调用的代码：
<img width="973" alt="4f67194d8abf4a318b3757a57126b37" src="https://user-images.githubusercontent.com/28804050/168040917-9ab023c2-7336-4c8b-94f7-03ad303ed056.png">
这是报错log：
<img width="1568" alt="4d47fb29559aeebbef5baa361ad9217" src="https://user-images.githubusercontent.com/28804050/168041019-4cc1e9d9-2cc7-47e1-a9df-8c0cbe312a13.png">

帮忙看下是不是最新更新这里了

**Comment by junjie-bianjie** [comment]
这个是网络异常。目前主网节点链接不稳定，我们正在抓紧修复

**Comment by seanxxcc** [comment]
用户反馈这个问题目前还没有解决，可能不是主网节点连接不稳定的问题，请继续协助排查 @zhangyelong @junjie-bianjie  

@akak774 请将近期碰到的最新报错和其他任何补充信息补充到这里。
