### ISSUE TITLE
账户返回余额不足

### ISSUE THREAD

**Issue by username-linyi** [bianjieai/opb-faq#50]
公司名称 [合肥市艾数大数据有限责任公司]
<img width="801" alt="54d40acc897bdbb0c55c356e3e5fe76" src="https://user-images.githubusercontent.com/57171529/168512309-ca19123d-3c7a-49a2-bf53-c56327082617.png">

**Comment by zhangyelong** [comment]
正在查看，请稍等

**Comment by sowhat061** [comment]
> 公司名称 [合肥市艾数大数据有限责任公司] <img alt="54d40acc897bdbb0c55c356e3e5fe76" width="801" src="https://user-images.githubusercontent.com/57171529/168512309-ca19123d-3c7a-49a2-bf53-c56327082617.png">

日志排查下来项目正常请求，未看到异常日志。麻烦提供下详细点请求日志输入输出参数

**Comment by BAige88** [comment]
创建链账户时报错{"error":{"code_space":"ACCOUNTS","code":"INTERNAL_ERROR","message":"internal error"}} #62
