### ISSUE TITLE
sdk-go 初始化Client失败

### ISSUE THREAD

**Issue by Chenxi97** [bianjieai/opb-faq#51]
![7d9f33dea2e51a2bd118b4526f6e377](https://user-images.githubusercontent.com/29818576/168519306-f3a57276-0969-4992-a0bc-873c4fb4223a.jpg)
 昨晚21:00到23:00期间无法初始化，今天才恢复正常

**Comment by zhangyelong** [comment]
网关节点故障所致，如果再次发现此类问题，可以在群里直接联系 BSN 的运维人员/运营人员，我们也会关注和跟进节点的修复进展，感谢反馈！
