### ISSUE TITLE
测试换成正式环境了之后获取不到信息

### ISSUE THREAD

**Issue by 15330403239** [bianjieai/opb-faq#52]
从测试账号换成正式账号之后，key、secert、接口地址都换了，但是正式返回null，也没有带错误信息
正式：
![image](https://user-images.githubusercontent.com/30230930/168553563-a2123476-1b11-4552-ab4a-6bca3fa22c64.png)
测试：
![image](https://user-images.githubusercontent.com/30230930/168553693-ed5cea15-a0dd-4e31-af8a-93705cbe515a.png)

**Comment by zhangyelong** [comment]
生产环境的「响应码」是多少

**Comment by zhangyelong** [comment]
这个是 Avata API 的响应码还是你们自己服务的？
是 Avata API 没有响应内容吗，那 Avata API 的响应码是什么？

**Comment by 15330403239** [comment]
301
