### ISSUE TITLE
timed out waiting for tx to be included in a block 这个异常是什么原因？

### ISSUE THREAD

**Issue by TechPursuer** [bianjieai/opb-faq#54]
java sdk方式发行NFT

**Comment by junjie-bianjie** [comment]
baseTx里有三种模式：commit ，sync，async

- commit会一直等区块打包后，然后返回给你响应，所以会出现超时，就是issue中的问题

-  sync：发送给区块链，区块链会做一些基础检查然后响应给你，代表他收到了这个信息，且这个信息是合法的，具体成不成功要看链上的执行，比如余额不足导致失败

- async：发送给区块链，直接返回收到了，不做任何前置检查

使用 sync、async能减少出现这个问题的频率，但是任然需要通过hash查询交易的链上状态

**Comment by prolenking** [comment]
close #54

**Comment by prolenking** [comment]
> baseTx里有三种模式：commit ，sync，async
> 
> * commit：会一直等区块打包后，然后返回给你响应，所以会出现超时，就是issue中的问题
> * sync：发送给区块链，区块链会做一些基础检查然后响应给你，代表他收到了这个信息，且这个信息是合法的，具体成不成功要看链上的执行，比如余额不足导致失败
> * async：发送给区块链，直接返回收到了，不做任何前置检查
> 
> 使用 sync、async能减少出现这个问题的频率，但是任然需要通过hash查询交易的链上状态

原因描述如上，生产上运行建议使用“sync上链 + 异步检查交易是否成功”的方式进行交易，理由有两点：
1. commit模式需要等待区块打包，交易的上链效率受制于链的出块速度，等待时间长，容易出现超时。
2. sync模式异步上链，可以在块未打包时不受阻塞地发送多笔交易，相对于commit模式来说，无阻塞、效率更高，一般来说使用sync模式能够得到正确的结果，这笔交易就能够被打包上链了，即使存在特殊情况导致交易未能上链，也能够通过“异步检查”来保证一致性。

**Comment by prolenking** [comment]
> baseTx里有三种模式：commit ，sync，async
> 
> * commit：会一直等区块打包后，然后返回给你响应，所以会出现超时，就是issue中的问题
> * sync：发送给区块链，区块链会做一些基础检查然后响应给你，代表他收到了这个信息，且这个信息是合法的，具体成不成功要看链上的执行，比如余额不足导致失败
> * async：发送给区块链，直接返回收到了，不做任何前置检查
> 
> 使用 sync、async能减少出现这个问题的频率，但是任然需要通过hash查询交易的链上状态

原因描述如上，生产上运行建议使用“sync上链 + 异步检查交易是否成功”的方式进行交易，理由有两点：
1. commit模式需要等待区块打包，交易的上链效率受制于链的出块速度，等待时间长，容易出现超时。
2. sync模式异步上链，可以在块未打包时不受阻塞地发送多笔交易，相对于commit模式来说，无阻塞、效率更高，一般来说使用sync模式能够得到正确的结果，这笔交易就能够被打包上链了，即使存在特殊情况导致交易未能上链，也能够通过“异步检查”来保证一致性。
