### ISSUE TITLE
java sdk有没有什么方法可以根据数据类别标识和数据对象标识去查NFT的交易hash

### ISSUE THREAD

**Issue by TechPursuer** [bianjieai/opb-faq#55]

**Comment by BAige88** [comment]
创建链账户报错{"error":{"code_space":"ACCOUNTS","code":"INTERNAL_ERROR","message":"internal error"}} #62

**Comment by junjie-bianjie** [comment]
详见下图，type和attrKey 别修改，抄图上的
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/49903386/174992469-1b5372ea-6cbf-4e80-8e53-af8182894d1a.png">
