### ISSUE TITLE
OPB-SDK-GO什么时候更新？

### ISSUE THREAD

**Issue by 17y** [bianjieai/opb-faq#56]
请问下 opb-sdk-go 什么时候更新1155和代付gas功能呢？看ddc-sdk-go已经领先很多feature了

**Comment by duanhairui** [comment]
opb-sdk-go 会在6月初进行更新上先， Avata 平台将在6月中旬支持 MT（1155）相关接口。
只要使用 Avata 平台，就可以使用 gas 代付机制
