### ISSUE TITLE
测试的账密url能够正常拿到数据   但是换成正式的，就提醒参数错误

### ISSUE THREAD

**Issue by zhangke110** [bianjieai/opb-faq#58]
{"data":{"task_id":"abcasfd1652803436","operation_id":"abcasfd1652803436"}}   除了换apikey等信息  其他代码没经过任何改变  不懂为什么   麻烦解答一下

**Comment by duanhairui** [comment]
参考这个答案  https://github.com/bianjieai/opb-faq/issues/13

**Comment by BAige88** [comment]
创建链账户时报错{"error":{"code_space":"ACCOUNTS","code":"INTERNAL_ERROR","message":"internal error"}} #62

**Comment by zhangyelong** [comment]
请问是否已解决
