### ISSUE TITLE
创建nft类别提示：FORBIDDEN 无访问权限

### ISSUE THREAD

**Issue by wenlingjoey** [bianjieai/opb-faq#59]
测试查询接口，创建地址接口，都正常，发布NFT接口也正常，创建NFT类似提示无权访问，有人知道这个问题吗？这个创建NFT里面的owner我是用的这个应用账号下生成的地址

**Comment by wenlingjoey** [comment]
请求路径：
string(55) "https://stage.apis.avata.bianjie.ai/v1beta1/nft/classes"

请求头：
array(4) {
[0]=>
string(29) "Content-Type:application/json"
[1]=>
string(41) "X-Api-Key:SzXHqS88stKCSMhFP1Da2VVvR87HHRm"
[2]=>
string(76) "X-Signature:c097ac3d263db8dba7bad56bd18cacf652d88fb93176d063ae29be801d662c17"
[3]=>
string(25) "X-Timestamp:1652870183781"
}

请求参数：

{"name":"xrwtsssssest","symbol":"test","description":"\u6d4b\u8bd5\u6d4b\u8bd5","uri":"https:\/\/www.xingyuankjcp.com\/uploads\/2022-05-14-02-57-20.jpg","uri_hash":"https:\/\/www.xingyuankjcp.com\/uploads\/2022-05-14-02-57-20.jpg","data":"testdata","owner":"iaa1zdves3x9wqml4rlgqyzyx3er8xlnnjdquzfgqe","operation_id":"B518701837810357"}

**Comment by wenlingjoey** [comment]
有大佬能帮忙看下嘛？

**Comment by duanhairui** [comment]
有报错信息么，建议把报错信息贴出来或者截图。咱们的api 参数最好做隐藏处理或者是打码哈

**Comment by zhangyelong** [comment]
检查一下签名方法里，对于**中文**的处理方式，应该需要指定**不做 UNICODE 编码**处理：
```php
json_encode($params, JSON_UNESCAPED_UNICODE);
```

**Comment by BAige88** [comment]
创建链账户报错{"error":{"code_space":"ACCOUNTS","code":"INTERNAL_ERROR","message":"internal error"}} #62
