### ISSUE TITLE
Node.js 服务端发起请求总是 authentication failed

### ISSUE THREAD

**Issue by chengpeiquan** [bianjieai/opb-faq#60]
Hi，我们公司今天刚把 Key 和 Secret 申请下来，联调的时候遇到了验证问题，对比 #13 提到的情况，没找出具体啥原因，能帮忙看看吗？

## 开发环境

环境|技术栈
:-:|:-:
Avata API|测试环境的 API Key 和 API Secret 和接口
项目|Node.js + Nest.js + TypeScript

## 问题描述

我这边是用 Node.js + TypeScript 作服务端，调用 Avata API 是用 [axios](https://github.com/axios/axios) 来发起请求，需要的请求头信息都在拦截器里统一处理的。

用了 [crypto-js](https://github.com/brix/crypto-js) 处理签名， 用 [nanoid](https://github.com/ai/nanoid) 作为请求体要用到的 operation_id 。

目前 Avata API 响应回来的信息一直是下面这个：

```bash
{
  error: {
    code_space: 'NFTP-OPEN-API',
    code: 'FORBIDDEN',
    message: 'authentication failed'
  }
}
```

比如请求 https://stage.apis.avata.bianjie.ai/v1beta1/account 这个接口，没有 Query ，Body 部分都是 string （下面的 `data` 就是 POST 请求的 Body ）

```ts
// 用的 Axios 发起的，打印出来的请求信息
{
  headers: {
    'Content-Type': 'application/json',
    'X-Api-Key': '*****',
    'X-Timestamp': 1652870969310,
    'X-Signature': '*****'
  },
  responseType: 'json',
  withCredentials: false,
  method: 'post',
  url: 'https://stage.apis.avata.bianjie.ai/v1beta1/account',
  data: { name: 'cpq', operation_id: '0RiM_ocMaWPLTsSP-yjLM' }
}
```

按照 API 签名算法 SHA256(Params+Timestamp+ApiSecret) 的格式，我在 TypeScript 里的格式是：

```ts
String(SHA256(`${JSON.stringify(shaData)}${timestamp}${avata.apiSecret}`))
```

这里的 shaData 是这个请求提取出来转化后的 Params 如下：

```ts
{
    path_url: "/v1beta1/account",
    body_name: "cpq",
    body_operation_id: "0RiM_ocMaWPLTsSP-yjLM"
}
```

所以 Params 部分用 `JSON.stringify` 序列化后是：

```ts
{"path_url":"/v1beta1/account","body_name":"cpq","body_operation_id":"0RiM_ocMaWPLTsSP-yjLM"}
```

和文昌链小助手都没看出是哪个地方出了问题……

**Comment by zhangyelong** [comment]
签名的方法请贴出来看下

**Comment by zhangyelong** [comment]
> {"path_url":"/v1beta1/account","body_name":"cpq","body_operation_id":"0RiM_ocMaWPLTsSP-yjLM"}

可能是排序的问题，其它语言的签名方法里都会对 JSON 的 Key 按照字典进行排序

**Comment by chengpeiquan** [comment]
> > {"path_url":"/v1beta1/account","body_name":"cpq","body_operation_id":"0RiM_ocMaWPLTsSP-yjLM"}
> 
> 可能是排序的问题，其它语言的签名方法里都会对 JSON 的 Key 按照字典进行排序

果然，排序后就成功了！十分感谢！

**Comment by BAige88** [comment]
创建链账户时报错
{"error":{"code_space":"ACCOUNTS","code":"INTERNAL_ERROR","message":"internal error"}}
