### ISSUE TITLE
[Avata]: 批量创建账号时，因传错了字段名，导致查询不到所有链账户

### ISSUE THREAD

**Issue by chengpeiquan** [bianjieai/opb-faq#61]
### 环境：
- 服务端  Node.js  v16.15.0
- Avata 测试环境

### 问题描述：

批量创建账号时，因传错了字段名，导致查询不到所有链账户

### 期望结果：

1. 是否可以在别的账号上复现该问题，还是只有我遇到了？
2. 现在我的账号查询不到链账户的结果，辛苦看看怎么回事，怎么解决？
3. 类似这种非法字段可否返回错误代码，不要认为成功？

### 复现步骤：

1. 调用 [批量创建链账户](https://apis.avata.bianjie.ai/#tag/Accounts/paths/~1accounts/post) 时，代码层面忘记改成 `count` ，所以传成了 `name` 字段给 Avata API（也就是  `name: 2` ），签名前拿到的 Params 是：

```ts
{
  body_name: 2,
  body_operation_id: 'hEPYayyVYsn74D5xxGdHJ',
  path_url: '/v1beta1/accounts'
}
```

>我自己对客户端发起的参数有校验，是我在网关请求 Avata API 的时候忘记改了 - - 也就是 Postman 传了 `count` ，我再传给 Avata 的时候传成了 `name`

2. 这个接口没有报错，不过返回的是一个奇怪的格式：

```json
{
    "accounts": [
        {
            "0": "i",
            "1": "a",
            "2": "a",
            "3": "1",
            "4": "8",
            "5": "7",
            "6": "5",
            "7": "l",
            "8": "l",
            "9": "5",
            "10": "n",
            "11": "a",
            "12": "6",
            "13": "a",
            "14": "6",
            "15": "n",
            "16": "y",
            "17": "7",
            "18": "9",
            "19": "n",
            "20": "w",
            "21": "l",
            "22": "g",
            "23": "h",
            "24": "2",
            "25": "k",
            "26": "s",
            "27": "r",
            "28": "6",
            "29": "s",
            "30": "j",
            "31": "v",
            "32": "9",
            "33": "l",
            "34": "9",
            "35": "n",
            "36": "y",
            "37": "n",
            "38": "t",
            "39": "m",
            "40": "s",
            "41": "3"
        }
    ],
    "operationId": "hEPYayyVYsn74D5xxGdHJ"
}
```

3. 这个时候再通过 [查询链账户](https://apis.avata.bianjie.ai/#tag/Accounts/paths/~1accounts/get) 查询已创建的链账户，就查不到了，返回 `0` 和空数组：

```json
{
    "offset": 0,
    "limit": 10,
    "totalCount": 0,
    "accounts": []
}
```

4. 我再通过 [创建链账户](https://apis.avata.bianjie.ai/#tag/Accounts/paths/~1account/post) 添加单个链账户，返回应该是创建成功了，但重复步骤 `3` ，还是查询不到链账户：

```json
{
    "account": "iaa14dc6g9vfksjrqff6k8tmekrff09ndup92dlznr",
    "name": "cpq",
    "operationId": "eYvPnTTdELGrDJcTWX5DP"
}
```

辛苦帮忙看看是怎么回事，应该怎么恢复我的数据 - -

**Comment by ajiang55** [comment]
批量创建链账户如果不传count,会默认count=1,至于传了name参数,并没有什么影响,看下你的结果,组合起来是一个account地址,是不是你对结果做了处理

**Comment by ajiang55** [comment]
至于查询不到,需要你看下查询的参数是否正确

**Comment by chengpeiquan** [comment]
> 至于查询不到,需要你看下查询的参数是否正确

找到原因了，我刚才对这个请求也指定了一个新的 operation_id ，所以查询不到结果，感谢！
