### ISSUE TITLE
[Avata]: [查询NFT过滤参数不生效，转让销毁NFT报api_key is not exist，其他操作没问题]

### ISSUE THREAD

**Issue by wiy2015** [bianjieai/opb-faq#64]
**查询NFT返回如下，查询参数没有生效，貌似返回的是所有数据**
{"data":{"offset":0,"limit":10,"total_count":6434,"classes":[{"id":"avata427ee5de4f9dfb9b168fc2b9e962a2ebec4a249d480308549e53fc7e8243b98a","name":"mint class","owner":"iaa19vlg6q77jc62v3mmk2msc9zrc6p8sakl5xplem","tx_hash":"C3BDA462C33F6656AC67836E46D6E8FCD391060C20C92C9021DB4AF829D03030","symbol":"","nft_count":0,"uri":"","timestamp":"2022-05-24 19:20:29 +0000 UTC"},{"id":"avata810b86e970050c65781ab014a81110b5abb2535dc2d8de2a1c82d619a9ab2fe3","name":"mint class","owner":"iaa19vlg6q77jc62v3mmk2msc9zrc6p8sakl5xplem","tx_hash":"B3E8A93372FB3143D3423C9DECD7F6413271021D96E8F68666E8EE8774ACA176","symbol":"","nft_count":6,"uri":"","timestamp":"2022-05-24 19:20:17 +0000 UTC"},{"id":"avata7cad01cc6dba733a6d090d69d49c1520c40e7da1bda4a3f79d5561d343901651","name":"吗咿呀嘿","owner":"iaa19pgpkyyqfac8hshr3fzx5acafd0u9vp67d","tx_hash":"F6E11AB2696021215C74C2EB7E4A520C4EA781AC1E5947CD93BF11564C33E04C","symbol":"mayiyahei","nft_count":0,"uri":"http://google.com","timestamp":"2022-05-24 17:12:33 +0000 UTC"},{"id":"avata53f27d8759ca100b0b6ae6e1344c1974af4d03b52e2552d9e089f7f1e37f7f1a","name":"测试产品","owner":"iaa1djn5xq7426c527qreyp5zqzgcxgrnpfd6z","tx_hash":"FE3A893198E052D9BA970033D095279054A7E238F8389A762AC0066890D4D9AA","symbol":"test_01","nft_count":0,"uri":"https://nft-cj2533.oss-cn-zhangjiakou.aliyuncs.com/2022.05/ca6h0fe9t42gketknv30.png","timestamp":"2022-05-24 17:06:37 +0000 UTC"},{"id":"avata287477beb2c0c708b4d68f8a73902591b88c08211ac6a0b18057c29a99ec5bf1","name":"ccccccc","owner":"iaa1td2qqc2e593d82pe9h7e9czsya3sd42yp9drd7","tx_hash":"FC314DC0E5B9FC13009BC834DDE5C899F01FCD98857752C399960B22422B2C07","symbol":"43r","nft_count":0,"uri":"https://nft-cj2533.oss-cn-zhangjiakou.aliyuncs.com/2022.05/ca6gg920kl1j2jv3c99g.jpeg","timestamp":"2022-05-24 16:30:48 +0000 UTC"},{"id":"avata1d0a4506c3dee7a32c562011320ca54e3c452340b75c58fa865322530c11c153","name":"测试","owner":"iaa1t5cjwcvwtezng5tawcx2g764nf67p97934et","tx_hash":"7F9BA400EA26429D2930A83F83D8A2F13D856F41157E39202209B4C4CA614DF1","symbol":"1036601","nft_count":0,"uri":"https://tiyimeta-dev.oss-cn-hangzhou.aliyuncs.com/commons/ffe392861e73406d9d8d34d38818b2c9.jpg","timestamp":"2022-05-24 15:25:53 +0000 UTC"},{"id":"avata28561f5bb8f6f5679e77cb121675a9bd365689dbc5093ef57555a420eebc13cc","name":"毛孔马上打开电视","owner":"iaa1td2qqc2e593d82pe9h7e9czsya3sd42yp9drd7","tx_hash":"47F87D67D5C9E8D5093DF6ADC650627E54FACE7BBA6322B409A082A7","symbol":"gghy","nft_count":0,"uri":"https://nft-cj2533.oss-cn-zhangjiakou.aliyuncs.com/2022.05/ca6fc920kl1j2jv3c980.jpg","timestamp":"2022-05-24 15:14:12 +0000 UTC"},{"id":"avata0c1ef2fb37e0dc1228b3f277e3fb53af6602a95821fc1ab72bc7c8d3eef076a1","name":"俱乐部勋章【全球限量】","owner":"iaa1m62h73vel0qcn8fzzpxqfqd3aef","tx_hash":"65643D44A233F282B05306E2EF52E37AABECA4110E39C866656202EF1DC8C1DF","symbol":"","nft_count":626,"uri":"","timestamp":"2022-05-24 13:42:46 +0000 UTC"},{"id":"avataaccbc3e2b5c458d0e495e59698eff794d941e517fede0282b9df3a0d3c6951f4","name":"俱乐部勋章【全球限量】","owner":"iaa1m62h73vel0qcn80cmj3f4ye3aef","tx_hash":"638D9AFC663FF4736B1A33FD0DC73965D3D20228A25B38071621B7D1AC3C8E31","symbol":"","nft_count":0,"uri":"","timestamp":"2022-05-24 13:37:35 +0000 UTC"},{"id":"avata7588e73fe0d9cad86bb9331d4afedd3555d65b49bbf19db5ad312a7301b8de59","name":"俱乐部勋章【全球限量】","owner":"iaa1m62h73vel0qcn80cmj3f4ye5tfzzpxqfqdash":"4110FEF7955D3B9ACCD85CE2D1817B4B1C19DDAD4F24BA69E903157A01928AE7","symbol":"","nft_count":0,"uri":"","timestamp":"2022-05-24 13:33:33 +0000 UTC"}]}}

转让NFT，销毁NFT {"error":{"code_space":"NFTP-OPEN-API","code":"FORBIDDEN","message":"api_key is not exist"}}status =  403 Forbidden
其他的没问题。

**Comment by zhangyelong** [comment]
请检查一下转让、销毁 NFT 请求的 HTTP Header 是否设置了 API Key

**Comment by TianYuChai** [comment]
你好，能否告知下是那个过滤参数没有生效？
