### ISSUE TITLE
测试环境创建链账户,查询链账户无法查询到

### ISSUE THREAD

**Issue by leecosy** [bianjieai/opb-faq#67]
创建链账户接口: /v1beta1/account
// 请求数据
{"name":"13605706992","operation_id":"16536300826350358100020"}
// 响应数据
{"data":{"account":"iaa1mdkkhjkyjsmfua7f32htuf9xd0dtztwkacd5yp","name":"13605706992","operation_id":"16536300826350358100020"}}

链账户查询接口: /v1beta1/accounts?offset=0&limit=10&operation_id=16536301907950358100023
// 响应数据
{"data":{"offset":0,"limit":10,"total_count":0,"accounts":[]}}

**Comment by leecosy** [comment]
创建NFT类别和查询NFT类别, 同样的问题. 查询不到自己创建的, 反而查询到别人创建的了

**Comment by zhangyelong** [comment]
> // 请求数据
> {"name":"13605706992","operation_id":"16536300826350358100020"}
> 链账户查询接口: /v1beta1/accounts?offset=0&limit=10&operation_id=16536301907950358100023

创建链账户使用的 operation_id 和查询链账户使用的 operation_id 不一样，operation_id 输入错误是查不到信息的

**Comment by zhangyelong** [comment]
> 创建NFT类别和查询NFT类别, 同样的问题. 查询不到自己创建的, 反而查询到别人创建的了

NFT 相关信息的查询，是全局的，如果想查询自己的，可以加筛选条件。
