### ISSUE TITLE
[SDK]: 批量发行nft的时候sdk没有报错,但是在文昌链浏览器中显示空白的失败

### ISSUE THREAD

**Issue by cmanyanc** [bianjieai/opb-faq#69]
### 问题描述：
批量发行nft的时候，sdk没有报错，且有返回hash。但是该hash在文昌链浏览器中显示空白的失败。nft也没有创建成功

### 复现步骤：
<img width="783" alt="image" src="https://user-images.githubusercontent.com/26475189/170839551-2a9c4c99-3a92-47e2-91ed-5c199f778e78.png">

### 补充信息：
B1EC0CD661C8A28DF03408A46B53FDECE2AEADB7752FAB24D8EAF85C79CCB40F
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/26475189/170839516-8c7106da-71db-4353-bd16-2206748a35ef.png">

**Comment by cmanyanc** [comment]
<img width="819" alt="image" src="https://user-images.githubusercontent.com/26475189/170839602-87b6975c-4a0d-43fb-bdfa-f2a5412cac15.png">

**Comment by junjie-bianjie** [comment]
日志里是否有异常，因为链上确实搜不到这个 hash

**Comment by junjie-bianjie** [comment]
怀疑是 节点出现了卡交易的问题，正常不会出现。目前在跟进

**Comment by prolenking** [comment]
针对代码的建议优化点有以下两点以供参考：
1. 将批量发送交易的模式改为将创建nft的msg批量地放在一笔交易中。
这样做的好处是既可以**提高链上创建nft的速度**，又可以**降低维护sequence的难度**
2. 在每一笔交易发起过后，通过txhash来查询跟进链上结果，如果上链失败，打印ResultQueryTx.TxResult.log这个字段，以供排查
