### ISSUE TITLE
关于销毁NFT,请求报异常问题

### ISSUE THREAD

**Issue by 770450630** [bianjieai/opb-faq#72]
delete 请求接口   报错
 Array
(
[error] => Array
(
[code_space] => NFT
[code] => NOT_FOUND
[message] => resource not found, nft_id: avatadf4rmv2ykvahl8wrct9thbgu1py not found
)
)

这个key 我是可以在测试链中查到的  并且我的账户都可以查到 但是就是报这个错误 麻烦各位大佬帮我分析下问题  这个参数我是肯定传了的   path：/v1beta1/nft/nfts/avata3051647b4faa4036e63bf63904ce6d92dce1760d06e782ad6c0766c9eef6c656/iaa1h74zsdpkynq70wdf3ah884flhrrtqy3efdvjnl/avatadf4rmv2ykvahl8wrct9thbgu1py

**Comment by ajiang55** [comment]
可以先调用nft查询接口,确认nftid是否存在, 状态是否正常?
