### ISSUE TITLE
[Avata]: 批量发行NFT接口报错{code_space: "NFTP-OPEN-API", code: "FORBIDDEN", message: "authentication failed"} 

### ISSUE THREAD

**Issue by hackun666** [bianjieai/opb-faq#73]
### 复现步骤：
`$path = '/v1beta1/nft/batch/nfts/' . $class_id;
            $query = "";
            $url = $domain . $path;
            $header = ['Content-Type:application/json'];
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_POST, true);
            $operation_id = 'createnft_' . time();
            $data = array(
                'name' => $nft['name'],
                'uri' => $nft['uri'],
                'uri_hash' => hash('sha256', $nft['uri']),
                'data' => $nft['data'],
                'recipients' => array(
                    array(
                        'recipient' => $owner,
                        'amount' => intval($nft['amount']),
                    )
                ),
                'operation_id' => $operation_id,
            );
            SignCurl($ch, $path, $query, $data, $header, $apiKey, $apiSecret);
            $datatext = json_encode($data, JSON_UNESCAPED_UNICODE);
            curl_setopt($ch, CURLOPT_POSTFIELDS, $datatext);
            $res = curl_exec($ch);`

**Comment by hackun666** [comment]
{
    "name": "批量测试",
    "uri": "http://guochuang-1311899294.cos.ap-shanghai.myqcloud.com/nftimg/1fe4139dae4bdf4d35fef16d25b63bbd_b.jpg",
    "uri_hash": "5898ccbd0827999e03c10ca4b5620651ef8b7b0451339bf8a1dae4bc12bcfe45",
    "data": "",
    "recipients": [
        {
            "recipient": "iaa188453n87rqtygrc3jrhal34sfgcr2488xc6nfd",
            "amount": 2
        }
    ],
    "operation_id": "createnft_1654333179"
}

**Comment by hackun666** [comment]
已解决

把recipients里的amount字段放在recipient字段前面

**Comment by MaricoHan** [comment]
解决方案：php用户暂时需要自己对请求体数组中按key排序，再签名
