### ISSUE TITLE
[SDK]: 查询地址能量余额无响应

### ISSUE THREAD

**Issue by akak774** [bianjieai/opb-faq#74]
### 问题描述：

opbClient.getBankClient().queryAccount(address)， 调用该方法查询地址能量余额的时候，一直没有响应
### 期望结果：

期望返回地址的余额信息
### 复现步骤：

直接调用上面的方法就可以

**Comment by prolenking** [comment]
请提供一下调用该方法的环境。

初步怀疑是网络原因。

**Comment by akak774** [comment]
> 

就是本地启动了一个项目，JDK1.8，SDK版本是0.1.11，你那边试试。

**Comment by prolenking** [comment]
经测试，sdk中此功能正常，与现版本文昌链环境适配良好

**Comment by akak774** [comment]
> 经测试，sdk中此功能正常，与现版本文昌链环境适配良好

我找到问题了，opbConfig.setRequireTransportSecurity(true)，这个如果设置为false，就会出现一直无响应的情况，按说应该报个错啊
