### ISSUE TITLE
在请求“转移”接口时报错：fee-grant not found: unauthorized

### ISSUE THREAD

**Issue by boatfly** [bianjieai/opb-faq#76]
sdk接入，在transfer时碰到的问题，我将我这边的执行步骤简单列了一下，看看哪里出了问题，谢谢：
1. 测试网平台账户：iaa1wgnvws7ej2weghq5pvve5y4few95dzh3xmxdfk
2.两个测试网普通股账户：iaa1slg47alqldf6z48qwqkd37l73fgyyv9fzv7wap 和 iaa1j7t07m8d4fnf5egylpqp2yraaelgq02l82m4lf
3.用平台账户发行了资产：denom=fbibsn00001

4.用平台账户mint了资产 denom=fbibsn00001 nftId=fbibsnshard00001 给普通用户：iaa1slg47alqldf6z48qwqkd37l73fgyyv9fzv7wap

5.现在要将 denom=fbibsn00001 nftId=fbibsnshard00001 的资产 transfer给普通用户 iaa1j7t07m8d4fnf5egylpqp2yraaelgq02l82m4lf
5.1 首先 执行了 grantAllowance，其中garenter=iaa1wgnvws7ej2weghq5pvve5y4few95dzh3xmxdfk，garentee=iaa1slg47alqldf6z48qwqkd37l73fgyyv9fzv7wap
resultTx = feeGrantClient.GrantAllowance(garenter, garentee, baseTx);
5.2 在执行transferNft时 baseTx.setFeeGranter("iaa1slg47alqldf6z48qwqkd37l73fgyyv9fzv7wap"); resultTx = nftClient.transferNFt(transferNFTRequest, baseTx); 
报错：
`irita.sdk.exception.IritaSDKException: log: iaa1slg47alqldf6z48qwqkd37l73fgyyv9fzv7wap not allowed to pay fees from iaa1wgnvws7ej2weghq5pvve5y4few95dzh3xmxdfk: fee-grant not found: unauthorized`

看看是不是在GrantAllowance的操作不对，或者缺少了什么步骤？

**Comment by sin3A** [comment]
GrantAllowance的操作是正确的，但是在transferNft时不太对
其中5.1执行完成后是iaa1wgnvws7ej2weghq5pvve5y4few95dzh3xmxdfk授权给iaa1slg47alqldf6z48qwqkd37l73fgyyv9fzv7wap
所以当iaa1slg47alqldf6z48qwqkd37l73fgyyv9fzv7wap执行transferNft时设置的付款方是iaa1wgnvws7ej2weghq5pvve5y4few95dzh3xmxdfk
