### ISSUE TITLE
创建nft分类 一直返回 DUPLICATE_REQUEST  重复请求 

### ISSUE THREAD

**Issue by zhaoliming1** [bianjieai/opb-faq#78]
### 环境：

- win7
- PHP

### 问题描述：
创建nft分类 一直返回 DUPLICATE_REQUEST  重复请求  查询上链交易接口返回null 

### 期望结果：
 什么情况

### 复现步骤：
示例：
$name = $this->request->param('name');
        $operation_id = $this->request->param('operation_id');
        $body = [
            "name" => "$name",
            "operation_id" => "$operation_id",
        ];
        // 请求头
        $headers = $this->SignCurl('/v1beta1/account',[],$body,[]);
        $jsonStr = $body ? json_encode($body) : ''; //转换为json格式
        $url = 'https://stage.apis.avata.bianjie.ai/v1beta1/account';
        $headers2 = [
            'Content-type: application/json',
            'X-Api-Key: '.$headers['X-Api-Key'],
            'X-Timestamp: '.$headers['X-Timestamp'],
            'X-Signature: '.$headers['X-Signature'],
        ];
        $options = [
            CURLOPT_HTTPHEADER => $headers2
        ];
        $res = Http::post("$url", "$jsonStr", $options);
        return $res;
2. name=亿生信分类  operation_id=1330000000010001 owner=iaa1q2jetkaw768qvjm8q8td9qkxh3kd0uzz7psfvx   class_id=one123
3. /v1beta1/nft/classes
4. string(118) "{"error":{"code_space":"NFT","code":"DUPLICATE_REQUEST","message":"duplicate request,operation_id: 1330000000010001"}}"

//查询上链交易结果
$operation_id = $this->request->param('operation_id');
$sys_url = config('site.url');
$body = [
    'operation_id'=>$operation_id,
];
// 请求头 https://apis.avata.bianjie.ai/v1beta1/tx/{operation_id}
$headers = $this->SignCurl('/v1beta1/v1beta1/tx',$body,'',[]);
$jsonStr = $body ? json_encode($body) : ''; //转换为json格式
$url = $sys_url.'/v1beta1/tx?operation_id='.$operation_id;
$headers2 = [
    'Content-type: application/json',
    'X-Api-Key: '.$headers['X-Api-Key'],
    'X-Timestamp: '.$headers['X-Timestamp'],
    'X-Signature: '.$headers['X-Signature'],
];
$options = [
    CURLOPT_HTTPHEADER => $headers2
];
$res = Http::GET("$url", "", $options);
$json = json_decode($res,'true');
dump($json);

//查询nft分类
$owner = $this->request->param('owner');
$sys_url = config('site.url');
$body = [
    'owner'=>$owner,
];
// 请求头
$headers = $this->SignCurl('/v1beta1/nft/classes',$body,'',[]);
$jsonStr = $body ? json_encode($body) : ''; //转换为json格式
$url = $sys_url.'/v1beta1/nft/classes?owner='.$owner;
$headers2 = [
    'Content-type: application/json',
    'X-Api-Key: '.$headers['X-Api-Key'],
    'X-Timestamp: '.$headers['X-Timestamp'],
    'X-Signature: '.$headers['X-Signature'],
];
$options = [
    CURLOPT_HTTPHEADER => $headers2
];
$res = Http::GET("$url", "", $options);
$json = json_decode($res,'true');
dump($json);

**Comment by zhangyelong** [comment]
1. operation_id 不能重复使用，即使是不同的接口也不行
2. '/v1beta1/v1beta1/tx' -> '/v1beta1/tx'
3. 查询上链结果的接口，operation_id 是 path 参数，不是 query 参数
