### ISSUE TITLE
[Avata]: [标题]批量销毁文昌链报 报错 400 Bad Request: "{"error":{"code_space":"NFT","code":"BAD_REQUEST","message":"invalid tag : invalid json format"}}"

### ISSUE THREAD

**Issue by susheng1** [bianjieai/opb-faq#80]
### 环境：

测试环境

### 问题描述：
传输的参数为:
NFTDeleteDTO(owner=iaa1hjjawwdu4eu5jzqapqhq7a3u296dwg62j4g0np, operation_id=ceshixiaohuiejissf001, nfts=[{"class_id":"avatasqvda0lmgsfostmafu7bafaadbq","nft_id":"avatashct9r7vpc3j9w7joxrjy9kukts"}])
但是 报错 400 Bad Request: "{"error":{"code_space":"NFT","code":"BAD_REQUEST","message":"invalid tag : invalid json format"}}"

### 期望结果：
希望可以通过

### 补充信息：
用的链接 :https://stage.apis.avata.bianjie.ai/v1beta1/nft/batch/nfts/
apiKey="72X2y0h552s6a0h5r4Y2C5z2d5w4c3t"
apiSecret="J2x2E0a5B2C6c0J5R4r2n5q2x5E4P3x"

**Comment by deadfiish** [comment]
已修复，可以重新请求试试。

**Comment by deadfiish** [comment]
可以重新请求试试
