### ISSUE TITLE
如何使用metamask和remix在文昌链进行开发，文昌链是否支持Truffle框架开发

### ISSUE THREAD

**Issue by alanding1006** [bianjieai/opb-faq#81]

**Comment by ajiang55** [comment]
文昌链支持 智能合约
文昌链 智能合约 开发文档:https://irita.bianjie.ai/docs/core_modules/evm.html

**Comment by alanding1006** [comment]
> 文昌链支持 智能合约 文昌链 智能合约 开发文档:https://irita.bianjie.ai/docs/core_modules/evm.html

这个文档我看了有详细一点的文档吗 比如我通过文昌链的私钥在metamask钱包该怎么填写rpc，还有此文档没有说是否支持turffle框架进行开发

**Comment by ajiang55** [comment]
文昌链支持部署solidity合约,turffle框架开发的合约当然也是支持的,而metamask钱包的使用就需要您自己发掘了

**Comment by crazyxrp** [comment]
> 文昌链支持部署solidity合约,turffle框架开发的合约当然也是支持的,而metamask钱包的使用就需要您自己发掘了

自己发掘什么鬼。。。

**Comment by Oahizoul** [comment]
楼上老哥是不是搞错了..remix开发 metamask签名，文昌链签名的逻辑和eth签名逻辑又不一样，这个两回事吧...
