### ISSUE TITLE
【合作协议】申请合作协议的要求及方法

### ISSUE THREAD

**Issue by jeff-zixuan** [bianjieai/opb-faq#82]
1、申请条件：合作协议的应用方必须**已进行充值并在链上发行超过100笔NFT**

2、申请方式：请将下述信息作为证明材料发送至mia@bianjie.ai

- 企业名称
- 上线应用链接（官网、小程序或其他可以找到该应用的链接）
- 对接证明，如控制台扣费截图，**或其他能够证明已经有实际业务上链的截图/文件**
![image](https://user-images.githubusercontent.com/54826891/174575091-8b2f671b-c701-4e59-8454-2fa844786c09.png)
（注：如提供扣费截图，交易类型必须是【发行NFT】，可在控制台的【资金交易明细】中筛选）

**Comment by yunshuwenchuang** [comment]
企业名称：四川联创云存科技有限公司
上线应用连接：[www.yunshuwenchuang.com](http://www.yunshuwenchuang.com/)

**Comment by yunshuwenchuang** [comment]
企业名称：四川联创云存科技有限公司
上线应用连接：[www.yunshuwenchuang.com](http://www.yunshuwenchuang.com/)
![图片1](https://user-images.githubusercontent.com/109420198/179354909-2641da6c-db49-45e7-8cee-4dd70edd6ed5.png)
![图片2](https://user-images.githubusercontent.com/109420198/179354911-2f8a15c6-6ae6-48dd-92a5-e4de3742bffc.png)
![图片3](https://user-images.githubusercontent.com/109420198/179354912-6a603f20-bcc6-42a0-b050-a00a190c5bd4.png)
[哈希值.xlsx](https://github.com/bianjieai/opb-faq/files/9125735/default.xlsx)

**Comment by lokami** [comment]
之前不是发行100个NFT就可以申请吗
