### ISSUE TITLE
上链交易结果查询返回status=3是什么意思？

### ISSUE THREAD

**Issue by wenchangyiyo** [bianjieai/opb-faq#95]
提交上链任务30分钟了，定时查看上链交易状态，每次接口返回都是空的，只有一个status=3
结构如下：

> array(1) {
  ["data"]=>
  array(9) {
    ["type"]=>
    string(8) "mint_nft"
    ["tx_hash"]=>
    string(0) ""
    ["status"]=>
    int(3)
    ["class_id"]=>
    string(0) ""
    ["nft_id"]=>
    string(0) ""
    ["message"]=>
    string(0) ""
    ["block_height"]=>
    int(0)
    ["timestamp"]=>
    string(0) ""
    ["tag"]=>
    NULL
  }
}

我再次尝试同样的参数请求上链，createNFT，提示我Duplicate Request，重复请求，请问是否有明确的返回状态说明？

**Comment by deadfiish** [comment]
status = 3 代表交易等待处理。可以看一下接口文档：https://apis.avata.bianjie.ai/#tag/%E4%BA%A4%E6%98%93%E7%BB%93%E6%9E%9C%E6%9F%A5%E8%AF%A2%E6%8E%A5%E5%8F%A3
