### ISSUE TITLE
[Avata]: [发布分类失败，提示：This account has not been activated yet.]

### ISSUE THREAD

**Issue by wenlingjoey** [bianjieai/opb-faq#98]
发布分类的时候，提示：This account has not been activated yet.

创建账户没问题，麻烦咨询下为什么呢

**Comment by deadfiish** [comment]
创建链账户接口是离线创建的，作为接收者不需要授权，链账户发起交易需要进行代付授权上链，这个提示是因为链账户还没被授权，可以使用查询链账户接口查询链账户的授权状态。
