### ISSUE TITLE
[Avata]: [标题]铸造NFT 我们只请求了一次API 但是在浏览器的交易记录里就会出现多笔交易

### ISSUE THREAD

**Issue by xuewuzhiijngych** [bianjieai/opb-faq#99]
1.创建链账户也是 本身我们是12W会员，后台却有17W个记录
这个会员数量是在控制台看的
ApiKey:62s2A0r760M9K0k6X3K6H0d9r9w1D82

2.只请求了一次铸造NFTAPI 但是在浏览器的交易记录里就会出现多笔交易,也会扣多笔钱
账户：iaa1cstvph89ym56weg2hmalquz98cnvj5z0dtww5t
浏览器查询记录:
![image](https://user-images.githubusercontent.com/49543373/178248346-1485e68b-0dcf-4f06-896c-0d7bd2f86914.png)

**Comment by deadfiish** [comment]
1.链账户数确实是十七万+
2.只请求了一次铸造NFTAPI 但是在浏览器的交易记录里就会出现多笔交易，这边看到是请求了多次接口，可以确认一下。
